= Updating Apps Deployed to CloudHub 2.0

Based on https://docs.mulesoft.com/runtime-fabric/1.12/app-versioning[Reviewing Application Versioning on Runtime Fabric^] (Link out from Beta docs) . 

*Last update* 15-Mar-22


When deploying an application to CloudHub 2.0, Runtime Manager automatically versions and creates a new _configuration_.

Application configurations enable you to:

* View the configuration change history of the application.
* Roll back the configurations to an earlier version if the currently applied configuration has issues or is unstable.
* View the application status.
+
Possible values are:
+
Running:: At least one replica is receiving traffic (Started state).
Not running:: None of the replicas are receiving traffic.
Unknown:: The target is disconnected.
* Make updates to a deployed application’s configuration, including:
+
** Application file
** Application deployment package version
** Deployment target settings, such as runtime version, number of replicas, and whether the application is running in cluster mode
** Public endpoint and TLS settings
** Resource allocations, including CPU and memory
** App property values
* View logs and diagnostics associated with a configuration.

== Update App Settings

include::partial$select-private-space.adoc[tag=selectAppsPage]
include::partial$select-private-space.adoc[tag=clickAppName]
include::partial$select-private-space.adoc[tag=clickSettings]
+
* The *Config changes* tab displays the changes to the successfully deployed application configuration and includes the last ten configuration deployments in order by configuration date.
A unique hash identifies each configuration in the history.
* The *All changes* tab displays a history of versions created from the configuration deployment and the actions performed on each version.
. Depending on the deployment target (shared or private space), change the deployed configuration:
+
** Specify runtime options, such as uploading a new application file or changing the deployment target and resource allocation.
** Change the public endpoint for the app.
** Change app behavior with properties.
** Enable TLS v1 and TLS v1.1.
** Disable app logs and metrics (private space only).
. Click *Apply Changes*.
+
A message appears at the top of the page indicating the configuration is in progress.
. Click *View Status* to view the <<replica-statuses,status>> for each replica in the deployment.

When the configuration is successfully applied and deployed, a message appears at the top of the page, with application status, configuration identifier, date, and replica status.
The new configuration appears in the *Config changes* list.

If the configuration updates fail to deploy, the message indicates that CloudHub 2.0 didn't apply the configuration, the configuration status is `Update failed`, and the configuration appears in the *Config changes* history without a label.

In failure cases, the deployment attempts to roll back to the last successful version of the configuration.
In some situations, the rollback might not succeed, and the configuration status is `Update failed`.




[[replica-statuses]]
== Replica Statuses

Started::
The replica is receiving traffic.
Pending::
The replica is waiting to start.
Starting::
The replica is starting.
Deleting::
The deletion of the replica is in progress.
Deleted::
The replica was deleted.
Stopping::
The replica is stopping.
Stopped::
The replica has stopped (it is not receiving traffic).
Failed::
The configuration failed to deploy.
Recovering:
The replica is attempting to restart after terminating.
The last successfully deployed configuration is retained until the new (desired) configuration is successfully deployed.
Desired::
WHAT IS THIS?

== Rolling Update vs. Recreate Deployment Model

Depending on the deployment model, CloudHub 2.0 applies new configurations as either:

* Rolling updates
+
Maintain availability by incrementally updating replicas.
Requires one additional replica's worth of resources to succeed.
+
This model means zero downtime while CloudHub 2.0 applies updates to the application.
+
Because CloudHub 2.0 applies updates as rolling updates, different application versions run simultaneously until the update completes.
For this reason, ensure that your applications can run multiple versions in parallel.
* Recreate
+
Terminate replicas before redeployment.
Redeployment is quicker and doesn't require additional resources.

== Roll Back to a Previous Successful Configuration

If a deployed configuration has issues, you can roll back to a previous successful version of the configuration.

[NOTE]
If this is the first deployment of the application,
the rollback version isn't defined.
In case of a failed deployment, the application remains in the failed status.

. Select the version to which to roll back from the *Config changes* history.
. Click *Apply Changes*.
+
The configuration moves to the top of the *Config changes* history list and displays the new deployment date, and it retains its original identifying hash.


== See Also

* xref:ch2-deploy-shared-space.adoc[]
* xref:ch2-deploy-private-space.adoc[]
* xref:ch2-manage-props.adoc[]
* xref:ch2-view-logs.adoc[]
* xref:ch2-view-diag.adoc[]
* xref:ch2-manage-schedules.adoc[]
