= CloudHub 2.0 REST API

*Last update* 28-Apr-22

*We will need to look at the IDs in the code examples before GA.*

== CloudHub 2.0 Functions

* *Private Spaces*
** Get the list of private spaces in the organization.
** Create a private space.
** Delete the private space.
** Get the details of a single private space.
** Update an existing private space.

* *Connections*
** Get the list of connections inside the private space.
** Create a private space connection that includes one or more VPNs.
** Delete the private space connection. 
** Get the private space connection.
** Update an existing private space connection.
** Download the connection guide for a VPN connection.

* *VPN*
** Add a VPN to an existing connection.
** Delete a VPN from a connection.
** Update a VPN connection.
** Get supported VPN configurations.


* *Transit Gateways*
** Get a list of transit gateways associated with a private space.
** Update a transit gateway.
** Remove a transit gateway.

* *Transit Gateway Attachments*

** Create and attach a new transit gateway to a private space.
** Get a list of all transit gateway attachments in a private space.
** Get the details of a single transit gateway attachment.
** Attach an existing transit gateway to a private space.
** Remove a transit gateway attachment from a private space.
** Update routes in a transit gateway attachment

* *TLS Contexts*
** Get the list of TLS contexts inside the private space.
** Create a TLS context.
** Delete the TLS context.
** Get the TLS context.
** Update an existing TLS context.

== Anypoint Runtime Manager Functions

*THIS SECTION NEEDS REVIEW BY APP MANAGER TEAM*

The CloudHub 2.0 management API (CloudHub 2.0 API) enables you to programmatically access the functions of Anypoint Runtime Manager, such as:

* Manage applications:
** Create, deploy, start, stop, list, and delete an application on CloudHub 2.0.
** Update application metadata, including the number of replicas, Mule runtime engine version, and system properties.
** Retrieve statistics for an application or replica.
** Retrieve application transactions and events for a transaction.
** Check for replay data, replay the flow for a transaction, and delete replay data for an application.
** Manage static IP addresses and release unused IP addresses associated with an application.
** Download the Mule package file for the application.
** Update, enable, disable, or run all or some schedules.


* Manage logs, notifications, and alerts:
** Add, update, or retrieve log levels for an application.
** Download the log file for an application or instance.
** Create, update, or retrieve a notification.
** Mark a notification as read or unread.
** Create, update, or delete an alert triggered by an application.
** Retrieve an alert and alert history.

* Retrieve additional information about:
** Supported Mule versions
** The current organization, including usage statistics
** Replicas, including thread dumps and regions
** Users, including permissions
** Available domain names


For an interactive reference that includes supported resources, methods, required properties, and expected responses, see the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/cloudhub-api/[CloudHub 2.0 API^] (Link out from Beta docs).

<update link>


The CloudHub 2.0 API manages only applications deployed to CloudHub 2.0.
To manage on-premises applications using the API, see https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/arm-rest-services[Runtime Manager REST Services^] (Link out from Beta docs).


== Use the CloudHub 2.0 API

Before getting started, familiarize yourself with operations for applications.

You can use any HTTP client with the CloudHub 2.0 API.
With Java, use the https://jersey.github.io/[Jersey client^] or http://hc.apache.org/httpclient-3.x/index.html[HttpClient^] with https://github.com/codehaus/jackson[Jackson^] for JSON support. (Links out from Beta docs)


=== Authenticate with the CloudHub 2.0 APIs

To access operations in the CloudHub 2.0 API, you must:

include::partial$ch2-api-authenticate.adoc[]


=== Deploy an App

To deploy an app to CloudHub 2.0, run the following `curl` command:

----
// POST Deploy an application:

curl --request POST 'https://anypoint.mulesoft.com/hybrid/api/v2/organizations/<org-id>/environments/<env-id>/deployments' \
--header 'Content-Type: application/json' \
--header 'Authorization: <bearer token>' \
--data-raw '{
    "name":"example",
    "target":{
       "provider":"MC",
       "targetId":"composer-space-shared",
       "deploymentSettings":{
          "clustered":false,
          "enforceDeployingReplicasAcrossNodes":false,
          "http":{
             "inbound":{
                "publicUrl":null,
                "pathRewrite":null
             }
          },
          "jvm":{
             "args":"-XX:MaxRAMPercentage=70.0 -XX:+PrintFlagsFinal"
          },
          "runtimeVersion":"4.5.0:20220221-1",
          "lastMileSecurity":false,
          "forwardSslSession":false,
          "updateStrategy":"rolling"
       },
       "replicas":1
    },
    "application":{
       "ref":{
          "groupId":"66310c16-bce5-43c4-b978-5945ed2f99c5",
          "artifactId":"app-scheduler-metadata-test",
          "version":"0.0.25",
          "packaging":"jar"
       },
       "integrations": {
         "services": {
            "objectStoreV2": {
                "enabled": true
            }
         }
       },
       "vCores": 0.1,
       "desiredState":"STARTED",
       "configuration":{
          "mule.agent.logging.service": {
            "applicationLogLevels": [
              {
                "artifactName": "app-with-2-schedulers",
                "scopeLoggingConfigurations": [
                  {
                    "logLevel": "INFO",
                    "scope": "com.food.hamburger"
                  },
                  {
                    "logLevel": "INFO",
                    "scope": "com.food.pizza"
                  },
                  {
                    "logLevel": "INFO",
                    "scope": "com.food.nuggets"
                  }
                ]
              }
            ]
          },
          "mule.agent.application.properties.service":{
             "applicationName":"example",
             "properties":{
                "test":"123"
             },
             "secureProperties":{
                
             }
          }
       }
    }
 }'
----

=== Modify an Attribute in a Private Space


To modify an attribute in a private space, run the following `curl` command:

----
curl --request PATCH 'https://anypoint.mulesoft.com/runtimefabric/api/organizations/<org-id>/privatespaces/<private-space-id>' \
--header 'Content-Type: application/json' \
--header 'Authorization: <bearer token>' \
--data-raw '{
    "environments": {
        "type": "all",
        "businessGroups": []
    }
}'
----

=== Add a Firewall Rule 


[IMPORTANT]
When you add a firewall rule, you must provide the complete list of rules
(existing and new rules) in the `managedFirewallRules` property.

To add a firewall rule to a private space, run the following `curl` command:

----
curl --request PATCH 'https://anypoint.mulesoft.com/runtimefabric/api/organizations/<org-id>/privatespaces/<private-space-id>' \
--header 'Content-Type: application/json' \
--header 'Authorization: <bearer token>' \
--data-raw '{
"managedFirewallRules": [
        {
            "cidrBlock": "0.0.0.0/0",
            "protocol": "tcp",
            "fromPort": 443,
            "toPort": 443,
            "type": "inbound"
        }
}'
----


=== Get a List of Applications

To get a list of apps deployed to CloudHub 2.0, run the following `curl` command:

----
// GET Application list:

curl --request GET 'https://anypoint.mulesoft.com/hybrid/api/v2/organizations/<org-id>/environments/<env-id>/deployments' \
--header 'Content-Type: application/json' \
--header 'Authorization: <bearer token>'

----

=== Get a Single Application

To get a single application deployed to CloudHub 2.0, run the following `curl` command:

----

curl --request GET 'https://anypoint.mulesoft.com/hybrid/api/v2/organizations/<org-id>/environments/<env-id>/deployments/<deployment-id>' \
--header 'Content-Type: application/json' \
--header 'Authorization: <bearer token>'

----


== Data Format

Resources and methods that return or accept a type use the JSON data format.

Here is an example of data received in JSON format in response to a request to get an application:

[source,json,linenums]
----
{
  "versionId": "xxxxxxxx",
  "domain": "hello",
  "fullDomain": "hello.usa-e1.cloudhub.io",
  "properties": {
    "foo":"bar"
  },
  "propertiesOptions": {},
  "status": "STARTED",
  "workers": {
    "type": {
      "name": "Micro",
      "weight": 0.1,
      "cpu": "0.1 vCores",
      "memory": "500 MB memory"
    },
    "amount": 1,
    "remainingOrgWorkers": 223.7,
    "totalOrgWorkers": 1000.0
  },
  "workerStatuses": [
    {
      "id": "i-xxxxxxxx",
      "host": "xxx.xxx.xxx.xxx",
      "port": 0,
      "status": "STARTED",
      "deployedRegion": "usa-e1",
      "staticIPEnabled": false
    }
  ],
  "lastUpdateTime": 1589868960908,
  "fileName": "hello.zip",
  "muleVersion": {
    "version": "4.3.0",
    "updateId": "xxxxxxxx",
    "latestUpdateId": "xxxxxxxx",
    "endOfSupportDate": 1633737600000
  },
  ...
}
----

== Rate Limits


The CloudHub 2.0 management API enforces global usage limits, with some exceptions.


[[global-rate-limits]]
=== Global Rate Limits for the CloudHub 2.0 Management API

The following table lists the rate limits for the CloudHub 2.0 management API endpoints except those listed in <<global-rate-limit-exceptions>>.

When the app reaches the rate limit, CloudHub 2.0 returns a 503 status code.

[%header,cols="20,20,20,10"]
|===
|Endpoints |Control Plane | Rate Limit Per Client IP Address | Status Code
.3+|All except specified endpoints|U.S.|75 requests per second  .3+| `503`
|EU .2+| 25 requests per second
|Government Cloud
|===

[[global-rate-limit-exceptions]]
=== Exceptions to the Global Rate Limits

The following table lists the exceptions to the <<global-rate-limits>>.

When the app reaches the rate limit, CloudHub 2.0 returns the status codes shown here.

[%header,cols="20,20,20,10"]
|===
|Endpoints|Control Plane | Rate Limit Per Client IP Address| Status Code
4+|*Endpoints under* `/api`
.3+|`/notifications`|U.S.|75 requests per minute .3+| `503`
|EU .2+|25 requests per minute
|Government Cloud
4+|*Endpoints under* `*v2/applications/{domain}*`
|`/logs` .4+|All .3+|10 requests per second  .3+| `429`
|`/deployments/{deploymentId}/logs`
|`/instances/{instanceId}/logs`
|`/instances/{instanceId}/log-file`|1 request per minute  | `500`
|===


== Status Codes and Error Handling

When you call the CloudHub 2.0 API, the following status codes are returned:

[%header,cols="10a,50a"]
|===
|Status Code |Description
|200 |The operation was successful.
|201 |The resource (such as an application) was created.

The `Location` header contains the location of the resource.
|404 |The resource was not found.
|409 |When creating a resource (such as a server, server group, or deployment), a resource with that name already exists.
|429 a|The operation was unsuccessful due to reaching the rate limit.
|500 |The operation was unsuccessful.

See the HTTP body for details.
|503 |The operation was unsuccessful due to a temporary condition, such as server overload or reaching a rate limit.

Retry the operation.
|===

When errors occur, such as a 500 status code, the HTTP response contains a JSON response with an error message:

[source,json,linenums]
----
500
Content-Type: application/json
Server: Apache-Coyote/1.1
Date: Mon, 10 Aug 2021 00:12:55 GMT

{
  message : "Some error message."
}
----


== See Also

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/cloudhub-api/[CloudHub 2.0 API^] (Link out from Beta docs)
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/access-management-api/[Access Management API^] (Link out from Beta docs)
* https://docs.mulesoft.com/runtime-manager/deployment-strategies.html[Deployment Options^] (Link out from Beta docs)
* xref:index.adoc[]
* xref:ch2-deploy.adoc[]
* xref:ch2-manage-apps.adoc[]
* https://docs.mulesoft.com/monitoring/[Anypoint Monitoring^] (Link out from Beta docs)
// * xref:developing-applications-for-cloudhub.adoc[]
