= Configuring Public Endpoints and Paths for Apps Deployed to a Private Space

*Last update* 30-Mar-22

[IMPORTANT]
CloudHub 2.0 supports customizing public endpoints only for apps that are deployed to private spaces, not shared spaces.


A private space routes requests from clients to apps deployed to the private space.

You can customize how these requests reach the app by configuring:

* Multiple custom public endpoints 
+
An _endpoint_ is the URL used to reach the app deployed to the private space,
for example `\https://my-app.example.com/`.
+
The administrator specifies the domains that you can use for the public endpoints 
by configuring the TLS context in the private space settings. 
For information, see xref:ps-config-domains.adoc[].

* Different paths for the app and the public endpoint URL
+
The _path_ is the base path expected by the HTTP Listener in your app, for example `my-app.example.com/v1/api`.
+
For information, see https://docs.mulesoft.com/http-connector/1.6/http-listener-ref[HTTP Listener Reference - Mule 4^]. (Link out from Beta docs)



[[before-you-begin]]
== Before You Begin

The administrator must set up the TLS contexts for the private space before you can configure the endpoints and paths for the app.

For information, see xref:ps-config-domains.adoc[].


[[configure-multiple-endpoints]]
== Configure Multiple Public Endpoints

You can enable your app to be reached via multiple public endpoints, for example,
`my-app.example.com` and `my-old-app.oldname.com`.

[TIP]
To ensure that each endpoint name is unique, use the `app-name` placeholder in the subdomain, 
or the path if the domain doesn't include a wildcard.

To configure multiple public endpoints:

. When deploying an app to a private space, click the *Ingress* tab.
+
See xref:ch2-deploy-private-space.adoc[].
. Configure the first endpoint:
.. Select the first domain from the *Domain* drop-down list, for example `&#x2a;.example.com`.
+
If the domain includes a wildcard, the *Subdomain* field becomes available.
.. Enter the subdomain, or enter the `my-app` placeholder in the *Subdomain* field to use the name of the app that you specified in the *Application Name* field as the subdomain.
+
For information, see <<placeholder-table,placeholders>>.
.. Enter the path where the HTTP Listener in the app is listening, for example `v1/api`.
. If you want to configure additional endpoints, click *Add Endpoint* and repeat steps 2.1 through 2.3. 
. Click *Deploy*.
. Verify that the app can be reached at each configured endpoint.

// === Placeholders
include::partial$deployment.adoc[tag=placeholders,leveloffset=+2]

[[configure-different-paths]]
== Configure a Different Path for the App and the Public Endpoint URL

You can configure different paths for the app and the public endpoint URL.
For example, the HTTP Listener in the app is listening on `my-app.example.com/v1/api` and you
want the app to be reachable from the internet using `my-app.example.com`.

To configure different paths:

. When deploying an app to a private space, click the *Ingress* tab.
+
See xref:ch2-deploy-private-space.adoc[].
. In the *Path* field, enter the path where you want the app to be reachable, for example, `/`.
. Enable *Rewrite Request Paths* and enter the target path expected by the app, for example,  `v1/api`.
. Click *Deploy*.
. Verify that the app can be reached at the new path.


[[path-rewrite-examples]]
=== Path Rewrite Examples

*_Can we get some real-world examples here?_*

[%header%autowidth.spread]
|===
|Target Path Value|Requests to... |Reach the App at...
| api | my-app.example.com | my-app.example.com/api
|===



[[remove-public-endpoint]]
== Remove a Public Endpoint 

To remove a public endpoint:

//SELECT APP SHARED
include::partial$select-private-space.adoc[tag=selectAppsPage]
. Click the *Ingress* tab.
. In the endpoint link row, click *X*.


[[view-private-endpoint]]
== View the Private Endpoint for an App

A private endpoint is accessible from inside the same private space or through
the VPN or transit gateway connection for the private space. 

To view or copy the URL for the private endpoint, hover over *private endpoint*:

<screenshot>

== See Also

* xref:ch2-deploy-private-space.adoc[]
* xref:ps-config-domains.adoc[]
* https://docs.mulesoft.com/http-connector/1.6/http-listener-ref[HTTP Listener Reference - Mule 4^] (Link out from Beta docs)


