= Deploying Apps to CloudHub 2.0

*Last update* 04-May-22

You can deploy Mule apps to either a shared or private space in CloudHub 2.0.

* xref:ch2-deploy-shared-space.adoc[]
* xref:ch2-deploy-private-space.adoc[]
* xref:ch2-download-test-app.adoc[]

[IMPORTANT]
include::partial$caveats.adoc[tag=supportedMule]

== Application Deployment

After triggering a deployment, the application status eventually changes to `RUNNING`.
If the application status never changes to `RUNNING`, the replicas contain a `state` and `reason` to indicate why the application status is not `RUNNING`.

When an application is deployed, the following events occur:

. The expected state of your application is stored, including application bundle and number of replicas.
. The application replica status is `PENDING`.
. When adequate compute and memory resources are available, each replica is attached to a node.
// If not already present, a Docker image corresponding to the Mule Runtime version is downloaded.
. The replica status is `STARTING`.
. The replica finishes loading the application.
. The replica status is `STARTED` and the replica can now perform work.

== Application Deployment Failure

If an application fails, for example, due to running of out memory, the following events occur:

. The replica status is `TERMINATED`.
. CloudHub 2.0 immediately attempts to restart the replica.
. The replica status is `RECOVERING`.

If the replica is able to restart:

. The replica finishes loading the application.
. The replica status is `STARTED` and the replica can now perform work.

If the replica can't restart, for example, it relies on a network resource which temporarily unavailable, the following events occur:

. The replica status is `PENDING`, with a message indicating "CrashLoopBackoff".
+
CloudHub 2.0 attempts to restart the replica, using exponential backoff to avoid an excessive number of restart attempts.
. The replica status alternates between `RECOVERING` and `PENDING` until the issue preventing a successful restart is resolved.
. The replica loads the application.

After a successful restart, the replica status is `STARTED` and the replica can now perform work.


== See Also

* xref:ch2-shared-space-about.adoc[]
* xref:ch2-private-space-about.adoc[]
