= CloudHub 2.0 for CloudHub 1.0 Users

CloudHub 2.0 improvements make it easier to learn, develop, and manage than CloudHub 1.0. Benefits include:

* Seamless Mule clustering for deployments with more than one replica
* Container-based application deployment to regulate resource consumption, ensure application availability, and enable scalability
* Deploying applications to shared spaces, which do not require advanced setup or infrastructure maintenance
* Amazon Web Services (AWS) service roles for resource access control
* More granular vCore purchase options
* Outbound firewall rule configuration
* Dedicated load balancer and ingress self-service logs

For a complete list of CloudHub 2.0 features, see xref:ch2-features.adoc[CloudHub 2.0 Features].

== Technical Enhancements from CloudHub 1.0 to CloudHub 2.0

The following improvements have been made to features that were also available in CloudHub 1.0:

* With the added fractional vCore offerings in CloudHub 2.0, you no longer must bundle multiple listeners in the same application to reduce your footprint.
* Unlike VPCs in CloudHub 1.0, you can associate a private space with multiple environments based only on the type of the environment, such as sandbox or production. You can now choose which environment type and individual business groups with which you share private spaces.
* Private spaces function as improved VPCs. Private spaces automatically get a private network for their applications as well as a configurable, private ingress load balancer. The ingress autoscales to accommodate traffic.
* By default, VPNs are now high availability.
* Applications now have xref:cloudhub-2::ch2-config-endpoints-paths.adoc[public and private endpoints] by default. You can also configure multiple public endpoints. You can access the endpoint addresses in Runtime Manager.
* You can make in-place edits and updates to TLS context and truststore of the ingress layer.
* In CloudHub 1.0, application names had to be unique globally per region. In CloudHub 2.0, the same application name can be used in different deployments in the same private space as long as they are in different environments or organizations.
* Custom log4j.xml is supported by default to enable streaming logs to external log collectors. You no longer must contact Support to enable or disable this feature.
* You can disable log streaming using Runtime Manager. You no longer must contact Support to enable or disable this feature. 
* Self-service logs for the dedicated load balancer and ingress are availllable. Titanium users can download logs through private spaces or Anypoint Monitoring.
* Using ports 80 and 443, applications inside a private space can communicate using internal load balancer via the private endpoint. Note that this depends on application protocol. 

== Considerations and Limitations

While CloudHub 2.0 has many improvements from CloudHub 1.0, organizations should consider the following nuances before switching.

=== Infrastructure Considerations

* CloudHub 1.0 VPC peering and direct connect have been deprecated in CloudHub 2.0. You can now use transit gateway attachments. Further, when you delete a private space that has a transit gateway attached, the transit gateway is preserved, and you can reattach it to a different private space.
* Anypoint Security, Secrets Manager, tokenizer, web application firewall (WAF) policies are not supported.
* Applications that are stopped still consume vCore licenses. To free vCores, delete applications that are not in use.
* To move applications between regions, you must redeploy another shared space or private space in a different region. You cannot move the app to a different region once deployed.
* xref:runtime-manager::deploying-to-cloudhub#copy-an-application-from-sandbox-to-production.adoc[Get From Sandbox functionality] is not supported.
* Insights are not supported. Use xref:monitoring::index.adoc[Anypoint Monitoring].
* Use port 8081 for HTTP and HTTPS traffic. 

=== Application Considerations

* Only Mule 4.3.0 through 4.4.x are supported. 
* Application bursting depends on the resource usage of other applications that are deployed in the private space and is not guaranteed. You must allocate vCores accordingly.
* Secure application properties are stored in encrypted, private vaults and cannot be viewed directly by users or MuleSoft staff after they are created. Secure properties are accessible only by the application itself. You can overwrite the properties to new values at any time.
* Use xref:mq::index.adoc[Anypoint MQ] for persistent queues and other queue management.
* HTTP and HTTPS inbound protocols are supported. Inbound protocols that are not HTTP-based are not supported.
* Private endpoints do not offer mTLS capabilities as internet-facing public endpoints.
* In application logs, you cannot search by correlation ID.
* Overwriting JVM parameters is not supported.
* Custom truststores are not supported.
* Application ingress path rewrite rules are not supported.
* xref:monitoring::log-points.adoc[Log points in Anypoint Monitoring] are not supported.
* Custom notifications and the CloudHub Connector are not supported.
* In xref:monitoring::alerts.adoc[Anypoint Monitoring], you must set alerts for apps individually. Setting alerts for all apps simultaneously is not supported.

== See Also

* xref:cloudhub-2::ch2-features.adoc[CloudHub 2.0 Features]
* xref:cloudhub-2::ch2-config-endpoints-paths.adoc[Endpoints]
* xref:cloudhub-2::ch2-private-space-about.adoc[Private Spaces]
* xref:monitoring::index.adoc[Anypoint Monitoring]
* xref:mq::index.adoc[Anypoint MQ]
* xref:runtime-manager::index.adoc[Runtime Manager]
