= CloudHub 2.0


CloudHub 2.0 is a fully managed, containerized integration platform as a service (iPaaS),
built on Anypoint Runtime Fabric, where you can deploy APIs and integrations.

== Why Deploy on CloudHub 2.0?

CloudHub 2.0:

* Provides for deployments across 12 regions globally.
* Dynamically scales infrastructure and built-in services up or down to support elastic transaction volumes.
* Builds in security policies, protecting your services and sensitive data with encrypted secrets, firewall controls, and restricted shell access.
* Encrypts certificates, passwords, and other sensitive configuration data at rest and in transit within Anypoint Platform.
* Provides a standardized isolation boundary by running each Mule instance and service as a separate container.

For CloudHub 2.0 pricing information, contact either your account executive or your account development representative.


== See Also

* xref:ch2-features.adoc[]
* xref:ps-create-configure.adoc[]
* xref:ps-gather-setup-info.adoc#private-network-region[Private Network Region]
