= CloudHub 2.0
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

// (*Learn more* link from *Private Spaces* page)


// reliability, performance, and security.


CloudHub 2.0 is a fully managed, containerized integration platform as a service (iPaaS)
where you can deploy APIs and integrations.

Built on Anypoint Runtime Fabric, which leverages Docker and Kubernetes,
CloudHub 2.0 provides 99.99% availability for deployments across 12 regions globally.

CloudHub 2.0 proactively scales each layer of infrastructure and services to support increasing transaction volumes, enabling performance adjustments for applications handling any type of workload. 
CloudHub 2.0 allocates the right amount of CPU and memory and, leveraging the benefits of containerization and the sidecar architecture, allows Mule instances to perform consistently under sustained load.

CloudHub 2.0 includes built-in load balancing and support for deploying 20 applications per CPU core, enabling you to grow your application network.

CloudHub 2.0 provides native support for Anypoint Security, protecting services and sensitive data with a powerful set of policies.
Integration with secrets manager ensures that certificates, passwords, and other sensitive configuration data are encrypted at rest and in transit, while providing centralized secrets management within Anypoint Platform.
By running each Mule instance and service as a separate container, CloudHub 2.0
provides a standardized isolation boundary. 


== See Also

* xref:ps-features.adoc[Features of CloudHub 2.0]
* xref:ps-create-configure.adoc[Create and Configure a Private Space]
* xref:ps-gather-setup-info.adoc#region[Region]
