= Runtime Fabric Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

// (*Learn more* link from *Private Spaces* page)

== What is a Private Space?

A _private space_ is a virtual, private, and isolated network hosted in the Runtime Fabric Cloud into which you deploy your apps.

Anypoint VPN (virtual private network) connects your private intranet to your private space to function as a single, private network. 
The VPN enables apps in the private space to access resources in your on-premises data centers behind your corporate firewall.
The VPN connection comprises two VPN tunnels between the private space in Anypoint Platform and a _gateway device_, a physical or software appliance located in your network.

When you create the private space, you associate a range of IP addresses for the apps in your private space to use and the region where they run. 
Private spaces support Amazon regions.
You can configure multiple private spaces in a single Amazon region, enabling you to set up separate isolated networks for your production and non-production environments, 
such as QA or staging.

You control the traffic to and from your private spaces. 
By default, Runtime Fabric Cloud blocks all traffic to the private space and provides firewall rules to allow connections through specified ports. 
You can configure additional firewall rules to control traffic to your private space, expose or block your custom ports, and block requests to your apps. 

The private space includes dedicated load balancers (DLB), which routes traffic to the private space.
You can configure DLBs to validate requests using your custom SSL certificates and enforce two-way SSL client authentication.
DLBs also enable you to map input URLs to call specific applications within the private space. 
With proxy rules, you can map your applications to a custom domain and host your apps under a single, vanity domain.


By combining firewall rules and DLB configuration, you can fine-tune how external services reach your applications.

== Private Space Connectivity 

You use an IPsec tunnel with network-to-network configuration to connect your on-premises data centers to your private space.

An IPsec VPN tunnel is generally the recommended solution for private space to on-premises connectivity, as it provides a standardized, secure way to connect.
This method also integrates well with existing IT infrastructure such as routers and appliances. 


== Anypoint Virtual Private Network 


Use Anypoint VPN to create a secure connection between your private space and your on-premises network.You can create multiple site-to-site VPNs if required. 

[NOTE]
The number of VPNs you can create depends on the VPN entitlements available to your account.
Contact your MuleSoft account representative if you don't know how many VPN entitlements you have on your account. 

Anypoint VPN supports site-to-site Internet Protocol security (IPsec) connections.
A physical or software appliance, called a VPN endpoint, is the terminator on your side of the connection.
The Anypoint side of the connection is an implementation of a virtual private gateway (VGW).
The MuleSoft VGW is associated with a single private space but can support up to 10 VPN connections. 

=== Anypoint VPN Features

Each Anypoint VPN connection consists of two tunnels that enable you to connect to a single public IP address at a remote location. To configure connectivity to an additional public IP address at a remote location, you must create two VPN connections.

A single VPN provides increased availability for your private space. Routine maintenance can briefly disable one of the two tunnels of your VPN connection. During this time, your VPN connection automatically fails over to the second tunnel so access is not interrupted. For this reason, both tunnels must be configured on your endpoint. Tunnel selection depends on your VPN endpoint capabilities and the routing type selection. 
 
The MuleSoft VGW implementation supports a maximum throughput of 1.25 Gbps. Multiple VPN connections to the same private space share the throughput capabilities of a single VGW. The VPN connection throughput depends on several factors, such as the capability of your VPN endpoint, the capacity of the connection, the average packet size, the protocol, and network latency between the gateways.

=== IPsec Settings

Anypoint VPN supports any combination of the following IPsec settings:

* IKE version 1
* IKE version 2 for route-based VPNs only
* AES 128 or 256-bit encryption operating in the Chain Block Cipher (CBC) mode
* SHA or SHA-2 (256) hashing
* Diffie-Hellman Phase1 groups 2, 14-18, 22, 23, 24
* Diffie-Hellman Phase2 groups 2, 5, 14-18, 22, 23, 24
* IKE (Phase 1) Lifetime: 28000 seconds (7 hours and 50 minutes)
* IPsec (Phase 2) Lifetime: 3000 seconds (50 minutes)

[NOTE]
Your endpoint must initiate traffic to establish and maintain the connection because the Anypoint VPN endpoint acts only as a responder.

=== Anypoint VPN Routing

Anypoint VPN supports dynamic or static routing for VPN connections.

* *Dynamic routing* Your device uses Border Gateway Protocol (BGP) to advertise routes to Anypoint VPN. Use BGP routing if your device supports this protocol.
* *Static routing* - Requires you to specify the routes (subnets) in your network that are accessible through Anypoint VPN. +
[NOTE]
A maximum of 95 route table entries is permitted per private space, regardless of the number of VPN connections. Consolidate networks to the fewest number possible to avoid exceeding the limit.  

=== VPN Limitations

Anypoint VPN does not support these features and configurations:

* Network Address Translation (NAT)
* IPv6
* IKEv2 with policy-based VPNs
* A single private space with both Direct Connect and Anypoint VPN connections
* Advertising a default route (0.0.0.0/0) over BGP or static routing

=== VPN Recommendations

* Adjust the maximum segment size of TCP packets entering the VPN tunnel.
+
VPN headers require additional space, which reduces the amount of space available for data.
+
To limit the impact of this behavior, configure your endpoint with TCP MSS Adjustment: 1387 bytes.
* Reset the `DF` flag on packets.
+
Packets might carry a Don't Fragment (`DF`) flag, indicating that the packet must not be fragmented. Some VPN devices can override the `DF` flag and fragment packets unconditionally when required. If available, enable the setting `Clear Don't Fragment (DF) Bit`.




== See Also

* xref:ps-create-configure.adoc[Create and Configure a Private Space]
* xref:ps-gather-setup-info.adoc#region[Region]
* xref:ps-config-fw-rules.adoc[Configure Firewall Rules to Allow Traffic to a Private Space]
* xref:ps-gather-setup-info.adoc#requirements-for-dynamic-vpn-connections[Requirements for Dynamic VPN Connections]
* xref:ps-gather-setup-info.adoc#requirements-for-static-vpn-connections[Requirements for Static VPN Connections]
* xref:ps-gather-setup-info.adoc#supported-gateway-devices[Supported Gateway Devices]
