= Complete the Network Admin Checklists
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Use the following checklists to gather information you'll need to set up your private network:

* <<Private Network Checklist>>
* <<VPN Checklist>>
* <<Internal DNS Servers Checklist>>
* <<VPN Connection Checklist>>


Complete the checklists to enable:

* Integration specialists to understand the information necessary to set up the private network and VPN
* Network administrators to understand and provide the required information

// (*View the checklist* link from *Private network* tab)
// Should this page include other network admin requests - Domains tab?

[cols="15a,10a,15a,15a,15a"]
.Private Space Configuration Template 
|===
5+|*Private Network Setup*
|Region     4+|
|CIDR Block 4+|
5+|*Virtual Private Network Setup*
.5+|Routing Type .2+| Dynamic | Remote ASN  2+|
                              | Local ASN   2+|
4+| *_OR_*
                 .2+| Static  | Static IP Prefixes 2+|
                              | Local ASN          2+|
.7+|Tunnel Configuration |Automatic 3+|
  4+| *_OR_*
                         .4+|Custom .2+| Tunnel 1 | Inside IP CIDRs |
                                                  | Pre-shared Keys |
                                    .2+| Tunnel 2 | Inside IP CIDRs |
                                                  | Pre-shared Keys |
|===


== Summary of Information Required to Set Up a Private Space

The following list summarizes the information required to set up a private space.
For details about each requirement, see the tables that follow.
 
* Private Network
+
** Region: `us-east-1`
** CIDR Block: `192.0.2.0/24`
* VPN
+
** Remote IP address: `198.51.100.0`
** Routing Type
+
*** Dynamic
+
**** Remote ASN: `65001`
**** Local ASN: `64512`
*** Static
+
**** Static IP Prefixes: `10.0.0.0/8`
**** Local ASN: `64512`
** Tunnel Configuration
+
*** Automatic
*** Custom
+
**** Inside IP CIDRs: `169.254.0.0/16`
+
***** Tunnel 1
***** Tunnel 2
**** Preshared Keys: `8740893_45`
+
***** Tunnel 1
***** Tunnel 2
* VPN Connection 
+
** Device vendor: Cisco
** Device platform: ASA 5500 Series
** Device software: ASA 8.2+
* Internal DNS Servers
+
** IP addresses: `208.67.111.111`
** Domains: `mulesoft.com`

== Private Network Checklist

Use the information in this checklist to configure the private network.
For information, see xref:ps-create-configure.adoc#create-a-private-network[Create a Private Network].

[%header,cols="20a,30a,20a,20a"]
.Private Network
|===
|Item |Description| Example |More Info  
|Region|The region to deploy your apps to|*US East (N. Virginia)*

(`us-east-1`)| <<Regions>>
|CIDR block| The range of IP addresses that your apps can use| `192.0.2.0/24` | <<CIDR Block>>
|===

== VPN Checklist 

Use the information in this checklist to configure the VPN.
For information, see xref:ps-create-configure.adoc#create-a-vpn[Create a VPN].


[%header,cols="20a,30a,20a,20a"]
.VPN
|===
|Item |Description | Example | More Info 
|Remote IP address|The public (single, static) IP address of your VPN endpoint | `198.51.100.0` |
|Routing type|Dynamic or Static||<<dynamic,Dynamic Routing Checklist>> 
<<static,Static Routing Checklist>>
|Tunnel configuration|Automatic or Custom||<<custom-tunnel,Custom Tunnel Checklist>>
|===

If your gateway device supports Border Gateway Protocol (BGP), select the dynamic routing type and complete this checklist.

See <<Requirements for Dynamic VPN Connections>>.

[[dynamic]]
.Dynamic Routing 
[%header,cols="20a,30a,20a,20a"]
|===
|Item |Description | Example | More Info 
|Remote ASN|The ASN that corresponds to your backend.|`65001` .2+| <<ASN>>
|Local ASN|A private ASN (64512–65534) to assign to the Anypoint Platform side |`64512`|
|===


Static routing requires you to specify the routes (subnets) in your network that are accessible through Anypoint VPN.

See <<Requirements for Static VPN Connections>>.


[[static]]
.Static Routing 
[%header,cols="20a,30a,20a,20a"]
|===
|Item |Description | Example | More Info 
|Static IP prefixes| The IP prefixes to advertise to your private network in Anypoint Platform, in CIDR notation| `10.0.0.0/8` |<<Static IP Prefixes>>
|Local ASN|A private ASN (64512–65534) to assign to the Anypoint Platform side |`64512`|<<ASN>>|
|===

[[custom-tunnel]]
.Custom Tunnel 
[%header,cols="20a,30a,20a,20a"]
|===
|Item |Description | Example | More Info 
|Inside IP CIDRs|The IP address range for the internal address of the VPN tunnel| `169.254.0.0/16` .2+|<<Custom Tunnel Configuration>>
|Pre-shared keys| |`8740893_45`||
|===

== Internal DNS Servers Checklist 

Use the information in this checklist to configure internal DNS servers.
For information, see xref:ps-create-configure.adoc#configure-internal-dns-servers[Configure Internal DNS Servers].


[[dns-servers]]
[%header,cols="20a,30a,20a,20a"]
.Internal DNS Servers
|===
|Item |Description | Example | More Info 
|IP addresses|The IP addresses of your internal DNS server |`208.67.111.111` .2+|<<Internal DNS Servers>>
|Domains|The domains to be resolved by the internal DNS server|`mulesoft.com`|
|===


== VPN Connection Checklist 

Use the information in this checklist connect a VPN to your corporate network.
For information, see xref:ps-create-configure.adoc#connect-a-vpn-to-your-corporate-network[Connect a VPN to Your Corporate Network].

[[vpn-connection]]
[%header,cols="20a,30a,20a,20a"]
.VPN Connection 
|===
|Item |Description | Example | More Info 
|Device vendor|The vendor of your network gateway device |Cisco .3+|<<Supported Gateway Devices>>
|Device platform|The platform of your network gateway device|ASA 5500 Series
|Device software|The software running on your network device|ASA 8.2+
|===


== Regions

The complete list of supported regions is:

[%header]
.Supported Regions 
|===
|Region|Sub-Domain
|US East (North Virginia)| `us-e1.cloudhub.io`
|US East (Ohio)| `us-e2.cloudhub.io`
|US West (Oregon)| `us-w2.cloudhub.io`
|US West (North California)| `us-w1.cloudhub.io`
|Canada (Central)| `ca-c1.cloudhub.io`
|Brazil (Sao Paulo)| `br-s1.cloudhub.io`
|Europe (Ireland)| `ir-e1.cloudhub.io`
|Europe (Frankfurt)| `de-c1.cloudhub.io`
|UK (London)| `uk-e1.cloudhub.io`
|Asia Pacific (Tokyo)| `jp-e1.cloudhub.io`
|Asia Pacific (Sydney)| `au-s1.cloudhub.io`
|Asia Pacific (Singapore)| `sg-s1.cloudhub.io`
|===

== CIDR Block 

The CIDR block is the range of IP addresses, in CIDR notation, that the apps deployed in your private space use. 

Because each app uses multiple IP addresses, allocate at least 10 IP addresses for each app.
If you're unsure how many apps will be deployed to the private space, contact your integration specialist. 

For example, to grant your private network 256 IP addresses between `10.111.0.0` and `10.111.0.255`, set the CIDR block to `10.111.0.0/24`.

When specifying CIDR blocks, ensure that the CIDR blocks:

* Are from a private IP space
* Don't overlap with any other CIDR blocks in your private spaces
* Don't overlap with any CIDR blocks in use in your corporate network

== ASN 

The Autonomous System Number (ASN) specifies the collection of routing prefixes.
For dynamic routing, configure both a remote and local ASN. 

Remote ASN::
The ASN corresponding to your backend.
You can use an existing ASN assigned to your network or a private ASN (64512–65534) that is not already assigned to your network.
The default value is 65001.
Local ASN::
An ASN for the Anypoint Platform side.
Use a private ASN (`64512–65534`) that is not already assigned to your network.
The default value is `64512`.

== Static IP Prefixes

A maximum of 95 route table entries is allowed per private network,
regardless of the number of VPN connections.
To avoid exceeding the limit, consolidate networks to the fewest number possible.


== Custom Tunnel Configuration

Inside IP CIDRs::
+
--
For each tunnel, enter the IP address range for the internal address of the VPN tunnel.

You can specify a size /30 CIDR block from the `169.254.0.0/16` range.
The CIDR block must be unique across all private network connections.

You cannot use the following reserved CIDR blocks:
----
169.254.0.0/30
169.254.1.0/30
169.254.2.0/30
169.254.3.0/30
169.254.4.0/30
169.254.5.0/30
169.254.169.252/30
----
--
Pre-shared keys::
+
--
For static connections, your VPN endpoint uses pre-shared keys (PSKs) to establish IKE Security Associations.

For each tunnel, enter a value of between 8-64 characters that does not begin with zero (0).
Use only alphanumeric characters, periods (.), and underscores (&#95;). 
--

== Supported Gateway Devices

A gateway device is a physical or software appliance on your organization's side of the VPN connection.
Your network administrator must configure the device to work with the Anypoint VPN connection.

The following gateway network devices are known to work with Anypoint VPN.
If your device does not appear in the list of tested devices,
check the requirements to verify that your device is suitable for use with Anypoint VPN.

[%header%autowidth.spread]
.Supported Gateway Devices 
|===
|Device Vendor | Device Platform | Device Software 
|Check Point | Security Gateway | R77.10 or later
.2+|Cisco | ASA | ASA 8.2 or later
|IOS | Cisco IOS 12.4 or later
|Dell | SonicWALL | SonicOS 5.9 or later
|Fortinet | Fortigate 40+ Series | FortiOS 4.0 or later
.4+|Juniper | J-Series Service Router | JunOS 9.5 or later
| SRX-Series Services Gateway | JunOS 11.0 or later
| SSG | ScreenOS 6.1 or 6.2 or later
| ISG | ScreenOS 6.1 or 6.2 or later
|Netgate | pfSense | OS 2.2.5 or later
|Palo Alto Networks || PANOS 4.1.2 or later
.6+|Yamaha .6+|| RT107e 
| RTX1200 
| RTX1210 
| RTX1500 
| RTX3000 
| SRT100 
.2+|Microsoft .2+|Windows Server| 2008 R2 or later 
|2012 R2 or later
.2+|Zyxel .2+|Zywall Series| 4.20 or later for statically routed Anypoint VPN connections 
|4.30 or later for dynamically routed Anypoint VPN connections
|===


=== Requirements for Static VPN Connections 

To create a static VPN connection, your VPN endpoint must be able to:

* Establish IKE Security Associations using a Pre-Shared Key (PSK) 
* Establish IPsec Security Associations in Tunnel mode
* Utilize any combination of IPsec settings that Anypoint Platform supports
* Fragment IP packets before encryption 
+
You must fragment packets that are too large to transmit. Your VPN device must be able to fragment packets before encapsulation.
* Use one Security Association (SA) pair per tunnel 
+
Anypoint VPN supports one unique SA pair per tunnel (a pair refers to one inbound and one outbound connection). Some policy-based devices create an SA for each ACL (access-control list) entry. In this situation, you must consolidate your rules and then filter unwanted traffic.
* Use IPsec Dead Peer Detection (DPD)
+
DPD allows devices to rapidly identify when network conditions change. You can enable DPD on the Anypoint Platform endpoint using `DPD Interval: 10` and `DPD Retries: 3`.
* Allow asymmetric routing 
+
Asymmetric routing occurs when routing policies send traffic from your network to the VPC through one tunnel and traffic returns from the VPC through the other tunnel.
The Anypoint Platform VPN endpoint selects the tunnel using an internal algorithm, making the return path dynamic.
If your device uses an active/active tunnel configuration, you must allow asymmetric routing for each Anypoint VPN connection.

=== Requirements for Dynamic VPN Connections

To create a dynamic VPN connection, in addition to the static VPN connection requirements, the VPN endpoint must be able to:

* Establish BGP peering
* Support route-based VPNs (bind tunnels to logical interfaces)


== Internal DNS Servers 

You can specify custom private domains by adding the IP address and domain name for your network.
When you provide private domains, your worker resolves them using your private DNS,
so you can still use the internal host names of your private network
(make sure your applications call the backend resources by FQDN).

IP addresses::
Up to three IP addresses of your internal DNS server.
// Add IP addresses for internal DNS servers, separated by commas. Multiple servers are allowed for redundancy. They should each support all domains added below.
Domains::
The common portion of your internal domain name, such as `mulesoft.com`.
// Add domains to be resolved by internal DNS, separated by commas.
