= Assign Roles and Permissions 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before you set up your private space, assign the required roles and permissions.
To assign roles and permissions, you need access to Anypoint access management. 

To set up and manage CloudHub 2.0, you must have one of the following:

* *Organization Administrators* role for the environments associated with the private space.
+
To specify this role, from Anypoint Platform, select *Access Management* > *Roles* > *Organization Administrators*, and then enter your user name to add it to the role.
* *Manage Private Spaces* permissions
+
--
To add these permissions:

.. From Anypoint Platform, select *Access Management* > *Users*, and then click your user name.
.. Click the *Runtime Manager* tab and then, for each environment, select *Manage Private Spaces* from the *Permission(s)* list.
--

You might also need the following permissions to enable inbound traffic to CloudHub 2.0:

* *Grant access to secrets*
* *Manage Secret Groups*
* *Read secrets metadata*
* *Write secrets*

To add these permissions, click the *Secrets Manager* tab on.

To deploy applications, you must have the *Exchange Contributors* role enabled for your Anypoint Platform account.

== See Also 

* https://docs.mulesoft.com/access-management/roles.html[Roles] (Link out from Beta docs)
