= Private Spaces
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

// (*Learn more* link from *Private Spaces* page)


A _private space_ is a virtual, private, and isolated area in CloudHub 2.0 in which to run your apps.
You can create multiple private spaces, either in the same or different regions.

You connect your private intranet to your private space to function as a single, private network. 

In each private space, you define:

* A _private network_, which is a virtual cloud where apps deployed to this private space run.
* A connection from the private network to your external network, either via Anypoint VPN or a transit gateway connection.
* *DNS target and TLS context* _need info here_
* Firewall rules to allow and block inbound and outbound traffic to your private space.
+
See xref:ps-config-fw-rules.adoc[].
* The environments and business groups to allow to deploy to the private space.
+
See xref:ps-config-env.adoc[].
* Where to forward logs, either Anypoint Monitoring or an external service such as Splunk.
+
See xref:ps-config-log-forwarding.adoc[].

// Utilize Anypoint Security Edge policies


== Private Network

When you create the private network, you associate a range of IP addresses for the apps in your private space to use, the region in which they run, and optionally, any internal DNS servers to resolve requests to custom domain.

Private spaces support Amazon regions.
You can configure multiple private spaces in a single Amazon region, enabling you to set up separate isolated networks for your production and non-production environments, 
such as QA or staging.

== Private Network Connections

You can connect a private space to your private network using the following methods:

* xref:ps-vpn-about.adoc[]
* xref:ps-tgw-about.adoc[]

[NOTE]
Before configuring routing, consolidate networks to the fewest number possible.
A maximum of 95 route table entries is allowed per private space,
regardless of the number of connections.


== Custom Domains and URL Rewriting


//// 

Custom domain
Create certificate for the domains you want to use.
Add Domains by creating TLS context
Keystore (PEM or JKS): public cert, private key, key password
Optional: CA path cert and Truststore
Ciphers, 

custom domains configured in the private space and ready to be used when deploying apps.

Use domains in deployed apps.

App deployed using default domain (under public endpoint)
Use the domains from the TLS context created for the private space
    Select domain from Host (all domains configured in the certificate uploaded in the TLS context appear in dropdown)
    Configure subdomain (* is default - uses the app name as the subdomain)
    App listening on the path
    Click on URL to see that the app is reachable on the configured path

    Configure multiple endpoints using other domains defined in the certificate - Add Endpoint

    App can be reached using multiple URIs

    Different public URL endpoint and different path for the app itself - path rewrite
    Customers reach the app at one URI but app listening at a different path.
        Enter the path to use for the customer in the Path (/api) and then enter the base path where the app listens in the Path Rewrite (/v1/api)



You can configure the private space to route traffic the apps deployed to the private space using a custom domain, configure the DNS target, upload create the TLS context.

A CloudHub dedicated load balancer provides an alternative domain name to route HTTP requests to Mule applications listening on port 8091 and HTTPS requests to Mule applications listening on port 8092. You can also use mapping rules to rename requests to the CloudHub DLB to a different Mule application domain name.


Configure HTTP Ingress
The edge gateway serves as the load balancer for both shared and private spaces. private spaces support the following:
URL rewriting
Vanity domains & TLS certificates
Setting policies on the Edge (DoS, WAF, CAP, etc)
Whitelist CIDRs that can send requests to load balancer:
Default: 0.0.0.0/0 for internet access



You configure the private space to validate requests using your custom SSL certificates and enforce two-way SSL client authentication.

DLBs also enable you to map input URLs to call specific applications within the private space. 
With proxy rules, you can map your applications to a custom domain and host your apps under a single, vanity domain.

////

== Firewall Rules

You control the traffic to and from your private spaces. 
By default, CloudHub 2.0 blocks all traffic to the private space and provides firewall rules to allow connections through specified ports. 
You can configure additional firewall rules to control traffic to your private space, expose or block your custom ports, and block requests to your apps. 

The private space provides load balancing to balance inbound traffic to apps across multiple replicas.

By combining firewall rules and TLS context configuration, you can fine-tune how external services reach your applications.



== See Also

* xref:ps-create-configure.adoc[]
* xref:ps-config-fw-rules.adoc[]
