= Assigning Permissions 


*Last update* 21-Jun-22

Before you set up your private space, ensure you have the required permissions 
assigned to your user account or a team to which you belong.
To assign permissions, you need access to Anypoint access management and Organization Administrator permissions.

* To set up and manage a private space, you need the CloudHub Network Administrator permission.
* To view a private space, you need the CloudHub Network Viewer permission.

Depending on your organization's permission structure, you can assign these permissions using the xref:access-management::teams.adoc[Teams] feature, the xref:access-management::users.adoc#grant-user-permissions[Roles] feature (deprecated), or by assigning an xref:access-management::users.adoc#grant-user-permissions[individual user permission].

Note that users who have the Organization Administrator permission can also view and manage all private spaces and additional privileges across Anypoint Platform. However, you should not assign this permission as a substitute for CloudHub 2.0-specific privileges. For more information, see xref:access-management::permissions-by-product.adoc[general permissions].

////
To deploy applications, you must have the *Exchange Contributor* role associated with your Anypoint Platform account.
////


== See Also 

* xref:access-management::index.adoc[]
