= Assign Roles and Permissions 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before you set up your private space, assign the required roles and permissions.
To assign roles and permissions, you need access to Anypoint access management. 

To set up and manage CloudHub 2.0, you must have one of the following:

* *Organization Administrators* role for the environments associated with the private space.
+
To specify this role, see https://docs.mulesoft.com/access-management/roles.html[Roles].
* *Manage Private Spaces* permissions
+
To add these permissions to a team, see https://docs.mulesoft.com/access-management/teams[Teams].


To enable inbound traffic to CloudHub 2.0, you might also need the following permissions:

* *Grant access to secrets*
* *Manage Secret Groups*
* *Read secrets metadata*
* *Write secrets*

To deploy applications, you must have the *Exchange Contributor* role associated with your Anypoint Platform account.

== See Also 

* https://docs.mulesoft.com/access-management/roles.html[Roles^] (Link out from Beta docs)
