= Configuring Advanced Private Space Settings

// *This topic is updated to the Design Spec dated 02-Mar-22*

*Last update* 10-Aug-22

Use options on the *Advanced* tab to:

* Configure how the ingress load balancer handles HTTP requests.
* Specify the read-response timeout.
+
This value is the amount of time CloudHub 2.0 waits for a response from the Mule application.
// If no data is sent or received in the specified time, CloudHub 2.0 closes the client and private space connections.
If no data is sent or received in the specified time, CloudHub 2.0 drops the request with a 504 error.
* Configure ingress load balancer logs levels and download logs.
* Configure Amazon Web Services (AWS) service roles.


== Configure HTTP Requests and Read-Response Timeout

When you modify HTTP requests, applications may not be reachable for up to 5 seconds.

// SELECT PRIVATE SPACE SHARED
include::partial$select-private-space.adoc[tag=selectPrivateSpace]
include::partial$select-private-space.adoc[tag=clickPrivateSpaceName]
include::partial$select-private-space.adoc[tag=clickAdvanced]
. Configure how the private accepts inbound traffic:
+
--
CloudHub 2.0 doesn't allow you to accept only insecure HTTP requests.

From the *HTTP Requests* list, select one of the following:

** *Redirect to HTTPS*
+
Redirects HTTP requests to the same URL using the HTTPS protocol.
** *Accept HTTP*
+
Accepts the inbound request on the default SSL endpoint using the HTTP protocol.
** *Drop HTTP*
+
Silently drops HTTP requests.
--
. Specify the read response timeout value.
+
The default timeout is 300 seconds.
+
. Click *Save Changes* or *Discard Changes*.

[[configure-ingress-load-balancer-log-levels]]
== Configure Default Ingress Load Balancer Log Levels 

CloudHub 2.0 enables you to specify the default severity level of messages that are written to the log file for all apps deployed to the private space.

[IMPORTANT]
More verbose log levels might affect performance.

// SELECT PRIVATE SPACE SHARED
include::partial$select-private-space.adoc[tag=selectPrivateSpace]
include::partial$select-private-space.adoc[tag=clickPrivateSpaceName]
include::partial$select-private-space.adoc[tag=clickAdvanced]
. Select the default <<ingress-load-balancer-log-levels,log level>> from the drop-down list.
. Click *Save Changes* or *Discard Changes*.

[[configure-custom-ingress-load-balancer-log-levels]]
== Configure Custom Ingress Load Balancer Log Levels 

CloudHub 2.0 enables you to specify the default severity level of messages that are written to the log file for specific IP addresses, for example, for troubleshooting.

[IMPORTANT]
More verbose log levels might affect performance.

// SELECT PRIVATE SPACE SHARED
include::partial$select-private-space.adoc[tag=selectPrivateSpace]
include::partial$select-private-space.adoc[tag=clickPrivateSpaceName]
include::partial$select-private-space.adoc[tag=clickAdvanced]
. Configure custom log levels:
+
.. Enter the IP address and select the <<ingress-load-balancer-log-levels,log level>> from the drop-down list.
.. Click *Add IP Address* to enter additional custom log levels.
.. To remove a custom log level, click the trash can icon (*Delete*) for the entry.
. Click *Save Changes* or *Discard changes*.


[[ingress-load-balancer-log-levels]]
== Ingress Load Balancer Log Levels

The default log level for IP address filtering is `DEBUG`.

[%header,cols="20a,60a"]
.Ingress Load Balancer Log Levels
|===
| Level 
| Description

// | All Priorities
// | All messages

| Error (Recommended)
| Only error messages, such as when an exception occurs

| Debug
| Debugging messages

| Trace
| Tracks application metadata such as path, headers, state, and timeline between Ingress and APIs to facilitate collaboration

| Info
| Informative messages

|===


[[download-ingress-load-balancer-logs]]
=== Download Ingress Load Balancer Logs

To download ingress load balancer logs:

// SELECT PRIVATE SPACE SHARED
include::partial$select-private-space.adoc[tag=selectPrivateSpace]
include::partial$select-private-space.adoc[tag=clickPrivateSpaceName]
include::partial$select-private-space.adoc[tag=clickAdvanced]
. Click *Download Logs*.


////
You can use Anypoint Runtime Manager to change the application log level by configuring the following property:
```
logging.level.<PACKAGE>=LEVEL
``` 
For example, if you use Runtime Manager to add the 
`logging.level.org.mule.service.http.impl.service.HttpMessageLogger=DEBUG` property, `DEBUG` level log information is emitted from `HttpMessageLogger`.
////

[[configure-aws-role]]
== Configure AWS Service Role

If you have identity and access management (IAM) roles configured in AWS, you can associate the role with your private space. The private space receives the permissions from the IAM role in AWS and can access AWS resources. To enable this feature, Anypoint Platform generates a unique role name you can use with AWS IAM. Note that you must allow outbound traffic on port 443 to use this feature. For more information, see https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html[IAM roles^].

// SELECT PRIVATE SPACE SHARED
include::partial$select-private-space.adoc[tag=selectPrivateSpace]
include::partial$select-private-space.adoc[tag=clickPrivateSpaceName]
include::partial$select-private-space.adoc[tag=clickAdvanced]
. Click *Enable AWS Service Role*.
. Click *Save Changes* or *Discard changes*.
+
A unique service role name is generated, and you can use this role configure to configure identity and access management for AWS. Role generation might take a few minutes. If the role name does not appear, refresh the page.

== See Also

* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html[IAM roles^] in the AWS documentation