= Configuring Advanced Private Space Settings

include::partial$feature-availability.adoc[tag=featureUnavailable]

*This topic is updated to the Design Spec dated 24-Nov-21*

*Last update* 10-Feb-22


Use options on the *Advanced* tab to:

* Configure how the private space handles HTTP requests.
* Specify the read-response timeout.
+
This value is the amount of time CloudHub 2.0 waits for a response from the Mule application.
If no data is sent or received in the specified time, CloudHub 2.0 closes the client and private space connections.

To configure advanced settings:

// SELECT PRIVATE SPACE SHARED
include::partial$select-private-space.adoc[tag=selectPrivateSpace]
include::partial$select-private-space.adoc[tag=clickPrivateSpaceName]
. Click the *Advanced* tab.
. Configure how the private accepts inbound traffic:
+
--
CloudHub 2.0 doesn't allow you to accept only insecure HTTP requests.

From the *HTTP Requests* list, select one of the following:

** *Redirect to HTTPS*
+
Redirects HTTP requests to the same URL using the HTTPS protocol.
** *Drop HTTP requests*
+
Silently drops HTTP requests.
** *Also accept HTTP requests*
+
Accepts the inbound request on the default SSL endpoint using the HTTP protocol.
--
. Specify the read response timeout value.
+
The default timeout is 300 seconds.
+
. Click *Save Changes* or *Discard Changes*.
