= Creating VPN Connections

To connect your private network to an external network using a 
VPN, create the VPN connection in the on the *Network* tab.

[NOTE]
After you create a VPN, you can't change any of the VPN settings,
except the static IP prefixes for static routing.

== Before You Begin

Before creating a VPN connection,
xref:ps-create-configure.adoc#create-private-network[create the private network].


[[create-vpn]]
== Create a VPN

//SELECT PRIVATE SPACE SHARED
include::partial$select-private-space.adoc[tag=selectPrivateSpace]
include::partial$select-private-space.adoc[tag=clickPrivateSpaceName]
. On the *Network* tab, in the *Connections* section, *Create Connection*.
. On the *Create Connection* page, select *VPN*, enter the xref:ps-gather-setup-info.adoc#vpn-name[name] in the *Connection Name* field, and click *Next*.
+
// Shared Connection Name
include::partial$create-config.adoc[tag=connectionNameReqs]
. On the *Create VPN Connection* page, enter the 
xref:ps-gather-setup-info.adoc#remote-ip-address[remote IP address] (a single, static IP address) for your VPN endpoint.
. Select the routing type:
+
xref:ps-gather-setup-info.adoc#dynamic-vpn-routing[Dynamic (BGP)]::
Select this option if your device supports Border Gateway Protocol (BGP).
BGP supports automatic failover for redundant connections.
+
.. In the *Local ASN* field, enter a xref:ps-gather-setup-info.adoc#local-asn[local private ASN] that isn't already assigned to your network.
+
If you have already created a VPN in this private space, the *Create VPN Connection* page doesn't display the *Local ASN* field.
.. In the *Remote ASN* field, enter a xref:ps-gather-setup-info.adoc#remote-asn[remote private ASN].
+
xref:ps-gather-setup-info.adoc#static-vpn-routing[Static]::
Select this option if your device doesn't support BGP.
+
.. In the *Local ASN* field, enter a xref:ps-gather-setup-info.adoc#local-asn[local private ASN] that isn't already assigned to your network.
+
include::partial$caveats.adoc[tag=localAsnNote]
+
.. In the *Static Routes* field, specify the (comma-separated) xref:ps-gather-setup-info.adoc#static-ip-prefixes[static IP prefixes] in CIDR notation.
+
Click *Show Existing Routes for this Network* to view the existing routes for the private network.
// +
// <screenshot>
. If you want to customize the tunnel configuration:
+
--
.. Expand *Advanced Options* and specify:

*** xref:ps-gather-setup-info.adoc#inside-ip-cidrs[IP ranges] (in CIDR format) for the internal address of each VPN tunnel.
*** xref:ps-gather-setup-info.adoc#preshared-keys[Pre-shared keys] (PSKs) for each VPN tunnel.

.. Select xref:ps-gather-setup-info.adoc#auto-tunnel-initiation[*Automatic Tunnel Initiation*] to specify that the VPN starts up automatically.
+
If you deselect this option, you must generate traffic from the customer gateway to establish VPN tunnels.
+
If you have already created a VPN in this private space, this option isn't available.
--
+
Any tunnel configuration values that you don't customize are set to the default.
. Click *Create VPN*. 
+
The VPN can take up to 15 minutes to create.
+
Once created, you can <<connect-vpn,connect the VPN to your corporate network>>
or you can click *Close* and complete this step later.


While the VPN is created, you can <<create-redundant-vpn,create a redundant VPN>>.

If the VPN creation fails, click *Create VPN* to try again.
. <<test-connection,Test the connection>> from your private space to the VPN.


[[connect-vpn]]
== Connect a VPN to Your Corporate Network 

After the VPN creation completes successfully, the tunnel status is *Down* until you 
connect the VPN to your corporate network.

To connect the VPN to your corporate network, you or your network administrator must configure
your gateway device outside of Anypoint Platform.

To facilitate this configuration, you provide information about your gateway device, which
Anypoint Platform uses to generate a connection guide to use to configure your device. 

After the VPN connection creation completes, the *Create VPN Connection* window
displays the *Connect VPN* step.
You can also display this page from the *Network* tab by clicking *View Connection Guide* or clicking the VPN menu (*...*) and selecting *Connection Guide*.

. Select options from the drop-down lists:
+
** *Device vendor*
** *Device platform*
** *Device software*

+
See xref:ps-gather-setup-info.adoc#supported-gateway-devices[Supported Gateway Devices].
. Click *Download Connection Guide*.
+
The connection guide, in `.txt` format, downloads to your local system.
. Give the connection guide to your network administrator to use to configure your gateway device.
+
For information, see https://docs.aws.amazon.com/vpc/latest/adminguide/Welcome.html[Your customer gateway device^] in the AWS VPN documentation.

[[create-redundant-vpn]]
== Create a Redundant VPN

If only one VPN has been configured, the *Network* tab displays an option 
to create a redundant VPN. 

MuleSoft strongly recommends that you create a redundant VPN. 
For information,
see xref:ps-vpn-about.adoc#vpn-ha[VPN High Availability].

Redundant VPNs inherit some settings from the intial VPN configuration automatically.

[IMPORTANT]
After you create a redundant VPN, you can't change any of the settings.

//SELECT PRIVATE SPACE SHARED
include::partial$select-private-space.adoc[tag=selectPrivateSpace]
include::partial$select-private-space.adoc[tag=clickPrivateSpaceName]
. On the *Network* tab, click *Create Redundant VPN*.
. On the *Create Redundant VPN Connection* page, complete the fields, based on the routing type of the initial VPN:
+
Dynamic (BGP)::
+
.. In the *Remote IP* field, enter the public IP address 
(a single, static IP address that isn't used by other VPNs) of your VPN endpoint.
.. In the *Remote ASN* field, enter a private ASN.
+
By default, *Remote ASN* contains the value from the first VPN, but you can change this value.
Static::
+
In the *Remote IP* field, enter the public IP address 
(a single, static IP address that isn't used by other VPNs) of your VPN endpoint.
+
Because you have already created a VPN in this private space, the *Create Redundant VPN Connection* page doesn't display the *Local ASN* field.

. If you want to customize the tunnel configuration, expand *Advanced Options* and specify:
+
--
** The IP ranges (in CIDR format) for the internal address of each VPN tunnel.
** The PSKs for each VPN tunnel.

[NOTE]
The redundant VPN uses the tunnel initiation option specified for the initial VPN.
--
+
Any tunnel configuration values that you don't customize are set to the default.

. Click *Create VPN*.

The redundant VPN can take up to 15 minutes to create.

If the redundant VPN creation fails, click *Create Redundant VPN* to try again.

[[test-connection]]
== Test the Connection to Your Private Space

After you create the VPN,
test the connectivity from CloudHub 2.0 to your networks.
To test the connection, use the Network Tools application.

For download and usage information about the Network Tools application, see https://help.mulesoft.com/s/article/How-To-Use-Network-Tools-Application[How To Use Network Tools Application^].

== See Also 

* xref:ps-gather-setup-info.adoc[]
* xref:ps-vpn-about.adoc[]
