= Enable Inbound Traffic to Your Apps Deployed to a Private Space	
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*This topic is in progress* 

include::partial$feature-availability.adoc[tag=featureUnavailable]


CloudHub 2.0 uses Transport Layer Security (TLS) contexts to encrypt 
inbound traffic to the private space.

Each TLS context includes:

* *Keystore*, which allows communication to your app using custom domains.
+
--
A keystore is a repository of security certificates (either authorization certificates or public key certificates), along with their corresponding private keys used, for example, in SSL encryption.

CloudHub 2.0 supports the following keystore types:

** JKS
** PEM
--
* *Truststore* (optional), which enables mutual TLS by identifying trusted external clients or private certificate authorities (CAs).
+
--
A truststore is a repository of security certificates from other parties that you expect to communicate with, or from Certificate Authorities that you trust to identify other parties.

CloudHub 2.0 accepts truststore files in PEM formats.
--

When you add the TLS context, you can select the ciphers to use with the TLS context.



== Before You Begin

* Update the name servers for your domains.
// https://docs.mulesoft.com/runtime-fabric/1.7/enable-inbound-traffic#step-1-configure-inbound-traffic-using-anypoint-runtime-manager	
* Create a CNAME record to route queries (if necessary).

== Configure DNS for Inbound Traffic Server

// === Configure Secure Domains for HTTPS Traffic

//SELECT PRIVATE SPACE SHARED
include::partial$select-private-space.adoc[tag=selectPrivateSpace]
include::partial$select-private-space.adoc[tag=clickPrivateSpaceName]
. Click the *Domains & TLS* tab.

////
. Configure how the load balancer accepts inbound traffic:
+
--
CloudHub 2.0 doesn't allow you to accept only insecure HTTP requests.

From the *Accept HTTPS requests* list, select one of the following:

** *Redirect HTTP to HTTPS*
** *Drop HTTP requests*
** *Also accept HTTP requests*
--
////

. Add TLS certificates:
// Add certificates so that you can use their domains when deploying apps to this private space.
+
[NOTE]
The `cloudhub-cert.pem` certificate is provided by default and can't be removed.

.. Click *Add certificate*.
.. Upload PEM files:
+
... Click *Browse* and upload a public certificate file from your local system.
... Click *Browse* and upload a private key file from your local system. 
... Enter the password for your key. 
+
Leave this field blank if your key isn't encrypted.
... Optionally, click *Browse* and upload a CA path certificate.
... Click *Add certificate*. 
.. Upload a JKS file:
+
... Click *Browse* and upload a keystore (JKS) file.
... Enter the keystore password and then click *Next*.
... Select an alias from the keystore to add the domains and then click *Next*. 
... Click the key password for the alias you selected.
... Click *Add certificate*.  
.. Import from Secrets Manager:
+
... Select the environment.
... Select the secret group.
... Click *Add certificate*.  
. Click *Advanced settings* to configure the log levels for the load balancer in the private space.
+
See <<Load Balancer Log Levels>>.
. Click *Save Domains*. 


== Load Balancer Log Levels 

CloudHub 2.0 enables you to specify the severity level of messages that are written to the log file.

[%header,cols="2*a"]
.CloudHub 2.0 Log Levels
|===
| Level 
| Description

| All Priorities
| All messages

| ERROR
| Only error messages, such when an exception occurs

| FATAL
| Only fatal messages when an application fails

| INFO
| Informative messages

| SYSTEM
| Messages about application and worker startup

| CONSOLE
| Messages about console events, such as setting the object store

| WARN
| Warning messages

| DEBUG
| Debugging messages
|===

You can specify log levels for a Mule application or API proxy during deployment.

////
You can use Anypoint Runtime Manager to change the application log level by configuring the following property:
```
logging.level.<PACKAGE>=LEVEL
``` 
For example, if you use Runtime Manager to add the 
`logging.level.org.mule.service.http.impl.service.HttpMessageLogger=DEBUG` property, `DEBUG` level log information is emitted from `HttpMessageLogger`.
////

== Validate: Verify Inbound Traffic Configuration


== See Also 

* xref:ps-config-log-forwarding.adoc[Configure Log Forwarding for a Private Space]
* xref:ch2-deploy.adoc[Deploy Apps to CloudHub 2.0]
* https://docs.mulesoft.com/mule-runtime/latest/tls-configuration[Configure TLS with Keystores and Truststores^] (Link out from Beta docs)
