= Gathering Required Setup Information

*Last update* 14-Feb-22

Use the following sections to gather the information you'll need to set up your private space.
For information about private spaces, see xref:ps-about.adoc[].

You might need to collaborate with your network administrator if you don't have access to this information.
In this case, share this setup checklist with them and provide an estimate of the number of apps you expect to deploy
to the private space for <<CIDR Block,CIDR block>> configuration.


// (*View the checklist* link from *Network* tab)
// Should this page include other network admin requests - Domains tab?

////

[NOTE]
====
The following two sections provide the same information in different formats:

* <<setup-info-private-space>>
* <<setup-info-private-space-table>>
====
////

[[setup-info-private-space]]
== Information Required to Set Up a Private Space

The following list summarizes the information required to set up a private space.
For details about each requirement, see the sections that follow.
 
*Private Network Setup*::
+
--
* <<private-space-name,Private space name>>
* <<private-network-region,Private network region>>
* <<cidr-block,CIDR block>>
* <<internal-dns-server,Internal DNS servers>> (optional)

** <<server-ip-addresses,IP addresses>>
** <<domains>>
--

*VPN Connection Type*::
+
--
* <<vpn-name, VPN name>>
* <<remote-ip-address,Remote IP>>
* *<<dynamic-vpn-routing,Dynamic Routing Type>>*

** <<local-asn>>
** <<remote-asn>>
* *<<static-vpn-routing,Static Routing Type>>*
** <<Local ASN>> (_first VPN only_)
** <<static-ip-prefixes,Static IP prefixes>> 
* *Automatic Tunnel Configuration* (_no configuration required_)
* *<<custom-tunnel-configuration,Custom Tunnel Configuration>>* (_optional_)

** Tunnel 1

*** <<inside-ip-cidrs,Inside IP CIDR>>
*** <<preshared-keys,Pre-shared key>>
** Tunnel 2
*** <<inside-ip-cidrs,Inside IP CIDR>>
*** <<preshared-keys,Pre-shared key>>

** *Supported Gateway Devices*
*** <<supported-gateway-devices,Device vendor>>
*** <<supported-gateway-devices,Device platform>>
*** <<supported-gateway-devices,Device software>>
--


*Redundant VPN Connection* (_optional_)::
+
--
* *<<dynamic-vpn-routing,Dynamic Routing Type>>*

** <<remote-ip-address,Remote IP>>
** <<remote-asn>>

* *<<static-vpn-routing,Static Routing Type>>*

** <<static-ip-prefixes,Static IP prefixes>> 
* *Automatic Tunnel Configuration* (_no configuration required_)
* *<<custom-tunnel-configuration,Custom Tunnel Configuration>>* (_optional_)

** Tunnel 1

*** <<inside-ip-cidrs,Inside IP CIDR>>
*** <<preshared-keys,Pre-shared key>>
** Tunnel 2
*** <<inside-ip-cidrs,Inside IP CIDR>>
*** <<preshared-keys,Pre-shared key>>

** *Supported Gateway Devices*
*** <<supported-gateway-devices,Device vendor>>
*** <<supported-gateway-devices,Device platform>>
*** <<supported-gateway-devices,Device software>>
--

*Transit Gateway Attachment Connection Type*::
+
--
* <<transit-gateway-name,Transit gateway name>>
* <<transit-gateway-region,Transit gateway region>>
* <<transit-gateway-routing,Transit gateway routing>>
* <<mulesoft-aws-account-id,MuleSoft AWS account ID>> 
* <<resource-share-id-owner,Resource share ID>>
* <<resource-share-id-owner,Resource share owner>>
--

[[setup-info-private-space-table]]
== Information Required to Set Up a Private Space (Table)


[cols="1,20a,20a,20a,20a,19a"]
.Private Space Configuration Form 
|===
6+|
6+h|Private Network Setup
.5+||<<private-space-name>> 4+|
|<<private-network-region>>     4+|
|<<cidr-block>> 4+|
.2+|<<internal-dns-server,Internal DNS server>>

(_optional_) |<<server-ip-addresses,Server IP addresses>> 3+|
|<<domains>>  3+|
6+h|VPN Connection Type
.14+|| <<vpn-name, VPN name>> 4+|
| <<remote-ip-address>> 4+|
|<<local-asn>> 4+|
|*<<dynamic-vpn-routing,Dynamic Routing Type>>* | <<remote-asn>> 3+|
^.^|*_OR_* 4+|
|*<<static-vpn-routing,Static Routing Type>>* | <<static-ip-prefixes>> 3+|
|*Automatic Tunnel Configuration* 4+| (_no configuration required_)
 .4+|*<<custom-tunnel-configuration,Custom Tunnel Configuration>>* (_optional_)   .2+| Tunnel 1 | <<inside-ip-cidrs,Inside IP CIDR>> 2+|
                                                | <<preshared-keys>> 2+|
              .2+| Tunnel 2 | <<inside-ip-cidrs,Inside IP CIDR>> 2+|
                                                 | <<preshared-keys>> 2+|
.3+|*<<supported-gateway-devices,Gateway Device>>*|Vendor 3+|
|Platform  3+|
|Software  3+|
6+h|Redundant VPN Setup
.14+|| <<vpn-name, VPN name>> 4+|
| <<remote-ip-address>> 4+|
|<<local-asn>> 4+|
|*<<dynamic-vpn-routing,Dynamic Routing Type>>* | <<remote-asn>> 3+|
^.^|*_OR_* 4+|
|*<<static-vpn-routing,Static Routing Type>>* | <<static-ip-prefixes>> 3+|
|*Automatic Tunnel Configuration* 4+| (_no configuration required_)
 .4+|*<<custom-tunnel-configuration,Custom Tunnel Configuration>>* (_optional_)   .2+| Tunnel 1 | <<inside-ip-cidrs,Inside IP CIDR>> 2+|
                                                | <<preshared-keys>> 2+|
              .2+| Tunnel 2 | <<inside-ip-cidrs,Inside IP CIDR>> 2+|
                                                 | <<preshared-keys>> 2+|
.3+|*<<supported-gateway-devices,Gateway Device>>*|Vendor 3+|
|Platform  3+|
|Software  3+|
6+h|Transit Gateway Attachment Connection Type
||<<transit-gateway-name,Transit gateway name>>    4+|
||<<transit-gateway-region,Transit gateway region>>    4+|
||<<transit-gateway-routing,Transit gateway routing>>    4+|
||<<mulesoft-aws-account-id,MuleSoft AWS account ID>>    4+|
||Resource share | <<resource-share-id-owner,ID>> 3+|
||| <<resource-share-id-owner,Owner>> 3+|
6+|
|===



[[private-network-requirements]]
== Private Network Requirements 

* <<private-space-name>>
* <<private-network-region>>
* <<cidr-block>>
* <<connection-type>>
* <<internal-dns-server>>

[[private-space-name]]
=== Private Space Name

Private space names can contain up to 60 alphanumeric characters (a-z, A-Z, 0-9), spaces, and hyphens (-).
Runtime Manager supports Unicode characters in private space names.

The private space name appears in the list when you select a deployment target for your apps.

You can rename a private space, if necessary.

[[private-network-region]]
=== Private Network Region

The _region_ is the Amazon region to deploy your apps to, such as `us-east-1`.

The complete list of supported regions is:

----
US East (Northern Virginia)
US East (Ohio)
US West (Northern California)
US West (Oregon)
Canada (Central)
South America (Sao Paulo)
Europe (Ireland)
Europe (Frankfurt)
Europe (London)
Asia Pacific (Singapore)
Asia Pacific (Sydney)
Asia Pacific (Tokyo)
----


////

The region to which you deploy your application determines the DNS record for your integration.
For example, if you deploy an application named `myapp` to Canada (Central),
the domain used to access the application is `myapp.ca-c1.cloudhub.io`. 

The complete list of supported regions is:

[%header]
.Supported Regions 
|===
|Region|DNS Record
|US East (Northern Virginia)| `us-e1.cloudhub.io`
|US East (Ohio)| `us-e2.cloudhub.io`
|US West (Northern California)| `us-w1.cloudhub.io`
|US West (Oregon)| `us-w2.cloudhub.io`
|Canada (Central)| `ca-c1.cloudhub.io`
|South America (Sao Paulo)| `br-s1.cloudhub.io`
|Europe (Ireland)| `ir-e1.cloudhub.io`
|Europe (Frankfurt)| `de-c1.cloudhub.io`
|Europe (London)| `uk-e1.cloudhub.io`
|Asia Pacific (Singapore)| `sg-s1.cloudhub.io`
|Asia Pacific (Sydney)| `au-s1.cloudhub.io`
|Asia Pacific (Tokyo)| `jp-e1.cloudhub.io`
|===
////


// CIDR Block Shared
[[cidr-block]]
include::partial$create-config.adoc[tag=cidrBlock,leveloffset=+2]


[[internal-dns-server]]
=== Internal DNS Server (Optional)

To enable apps deployed to a private space to access
internal resources that are not reachable from the public internet, 
configure domain resolution for your internal networks.

To configure the internal DNS server, specify the IP address for your internal 
domain server and the internal domains that you want to access from the private space.
The private space resolves the domains using the specified DNS server, 
enabling you to use internal host names in your private network
as long as your applications use the FQDN to request back-end resources. 

[[server-ip-addresses]]
==== Server IP Addresses

The _Server IP addresses_ identify the internal name servers that respond to DNS queries for the specified internal domains.

To provide redundancy, you can configure multiple internal DNS servers.

When configuring the IP addresses for the DNS servers, keep the following in mind:

* You configure DNS servers within a private space, so the server IP addresses you configure must be reachable from the private space.
+
If the server isn't reachable, DNS resolution fails.
* If you configure multiple servers, the private space queries any DNS server in the list for the specified domains at any time, in any order.
* All name servers must present the same DNS record.
* After the private space receives a valid response from any configured name server, it doesn't retry the request.
+
If one of the name servers doesn't have a record for the domain,
it returns the response `NXDOMAIN` (non-existent domain).
Because this response is valid, the private space doesn't send the query
to the other servers. 

[[domains]]
==== Domains

_Domains_ identify the internal domains that must be accessible from the private space.
The configured internal DNS servers resolve the specified domains, and the 
external DNS server resolves all other domains.

To specify an internal domain, use the second-level domain name, such as `mulesoft.com`.

[NOTE]
The total number of characters for all configured domains is 229.

[[connection-type]]
=== Connection Type

* <<vpn-requirements,Virtual Private Network (VPN)>>
* <<tgw-requirements,Transit Gateway Attachment>>

[[vpn-requirements]]
== VPN Requirements 

* <<vpn-name>>
* <<remote-ip-address>>
* <<dynamic-vpn-routing>>
* <<static-vpn-routing>>
* <<local-asn>>
* <<remote-asn>> (dynamic routing only)
* <<static-ip-prefixes>> (static routing only)
* <<inside-ip-cidrs>> (custom tunnel configuration only)
* <<preshared-keys>> (custom tunnel configuration only)
* <<supported-gateway-devices>>

[[vpn-name]]
=== VPN Name 

The _VPN name_ is the name of the VPN connection.


[[remote-ip-address]]
=== Remote IP Address 

The _remote IP address_ is the public (single, static) IP address of your VPN endpoint.

[[dynamic-vpn-routing]]
=== Dynamic VPN Routing (BGP)

For dynamic routing, your device uses Border Gateway Protocol (BGP) to advertise routes to Anypoint VPN.
If your device supports BGP, select dynamic routing. 

To create a dynamic VPN connection, in addition to the static VPN connection requirements, 
your VPN device must be able to:

* Establish BGP peering
* Support route-based VPNs (bind tunnels to logical interfaces)

////
Dynamic (BGP) Routing Type option should link to an explanation of the difference between routing types, especially related to how they handle failover when a redundant VPN exists.
////

[[static-vpn-routing]]
=== Static VPN Routing

Static routing requires you to specify the routes (subnets) in your network that are accessible through Anypoint VPN.

To create a static VPN connection, your VPN endpoint must be able to:

* Establish IKE Security Associations using a Pre-Shared Key (PSK) 
* Establish IPsec Security Associations in Tunnel mode
* Use any combination of IPsec settings that Anypoint Platform supports
* Fragment IP packets before encryption 
+
You must fragment packets that are too large to transmit.
+
Your gateway device must be able to fragment packets before encapsulation.
* Use one Security Association (SA) pair per tunnel 
+
Anypoint VPN supports one unique SA pair (one inbound and one outbound connection) per tunnel.
Some policy-based devices create an SA for each ACL (access-control list) entry.
In this situation, you must consolidate your rules and then filter unwanted traffic.
* Use IPsec Dead Peer Detection (DPD)
+
DPD allows devices to rapidly identify when network conditions change.
You can enable DPD on the Anypoint Platform endpoint using `DPD Interval: 10` and `DPD Retries: 3`.
* Allow asymmetric routing 
+
Asymmetric routing occurs when routing policies send traffic from your network to the VPC through one tunnel and traffic returns from the VPC through the other tunnel.
The Anypoint Platform VPN endpoint selects the tunnel using an internal algorithm, making the return path dynamic.
If your device uses an active/active tunnel configuration, you must allow asymmetric routing for each Anypoint VPN connection.


[[local-asn]]
=== Local ASN 

The _local ASN_ (Autonomous System Number) specifies a private ASN (`64512–65534`) to assign to the Anypoint Platform side of the VPN.

Use a private ASN that is not already assigned to your network.
The default value is `64512`.

[NOTE]
You configure the local ASN for both static and dynamic routing.

include::partial$caveats.adoc[tag=localAsnNote]
For subsequent VPNs that you create in the private space,
the *Local ASN* option is not available for static routing.

To change the local ASN after creating the VPN,
you must delete all existing connections first.

////
Local ASN is a property of the VPN gateway, which is used for all VPNs in a private space and must be created with its first VPN. The only opportunity to set the Local ASN is when the VPN gateway is created.

However, to answer your second question, Michelle said that users can set a different Local ASN when creating a VPN if they delete all existing connections first, presumably because we'll create a new VPN gateway at that point.
////

[[remote-asn]]
=== Remote ASN

The _remote ASN_ specifies a private ASN that corresponds to your backend.

[NOTE]
You configure the remote ASN only for dynamic routing. 

Use either an existing ASN assigned to your network or a private ASN (`64512–65534`) that is not 
already assigned to your network.
The default value is `65001`.

[[static-ip-prefixes]]
=== Static IP Prefixes

The _static IP prefixes_ are IP prefixes to advertise to your private network in Anypoint Platform,
in CIDR notation.

[NOTE]
You configure the static IP prefixes only for static routing.

A maximum of 95 route table entries is allowed per private network,
regardless of the number of VPN connections.
To avoid exceeding the limit, consolidate networks to the fewest number possible.

[[custom-tunnel-configuration]]
=== Custom Tunnel Configuration (Optional)

Select custom tunnel configuration if you want to specify custom values for
inside IP CIDRs and pre-shared keys.

Any values that you don't specify are autogenerated.

If you select automatic tunnel configuration, all values are auto-generated.

[[inside-ip-cidrs]]
==== Inside IP CIDRs

The _inside IP CIDRs_ is the IP address range for the internal address of the VPN tunnel.

[NOTE]
You specify the inside IP CIDRs only for custom tunnel configuration. 
For automatic tunnel configuration, these values are auto-generated.

For each tunnel, enter the IP address range for the internal address of the VPN tunnel.

You can specify a size /30 CIDR block from the `169.254.0.0/16` range.
The CIDR block must be unique across all private network connections.

You cannot use the following reserved CIDR blocks:

----
169.254.0.0/30
169.254.1.0/30
169.254.2.0/30
169.254.3.0/30
169.254.4.0/30
169.254.5.0/30
169.254.169.252/30
----

[[preshared-keys]]
==== Pre-shared Keys

A _pre-shared key_ (PSK) is a shared secret which was previously shared between 
two ends of a connection for the VPN tunnels.

[NOTE]
You specify the PSK only for custom tunnel configuration. 
For automatic tunnel configuration, these values are auto-generated.

For static connections, your VPN endpoint uses pre-shared keys (PSKs) to establish IKE Security Associations.

For each tunnel, enter a value of between 8-64 characters that does not begin with zero (0).
Use only alphanumeric characters, periods (.), and underscores (&#95;). 



[[supported-gateway-devices]]
=== Supported Gateway Devices

A _gateway device_ is a physical or software appliance on your organization's side of the VPN connection.

Your network administrator must configure the device to work with the Anypoint VPN connection.

The following gateway network devices are known to work with Anypoint VPN.
If your device does not appear in the list of tested devices,
check the requirements to verify that your device is suitable for use with Anypoint VPN.

[%header%autowidth.spread]
.Supported Gateway Devices 
|===
|Device Vendor | Device Platform | Device Software 
|Check Point | Security Gateway | R77.10 or later
.2+|Cisco | ASA | ASA 8.2 or later
|IOS | Cisco IOS 12.4 or later
|Dell | SonicWALL | SonicOS 5.9 or later
|Fortinet | Fortigate 40+ Series | FortiOS 4.0 or later
.4+|Juniper | J-Series Service Router | JunOS 9.5 or later
| SRX-Series Services Gateway | JunOS 11.0 or later
| SSG | ScreenOS 6.1 or 6.2 or later
| ISG | ScreenOS 6.1 or 6.2 or later
|Netgate | pfSense | OS 2.2.5 or later
|Palo Alto Networks || PANOS 4.1.2 or later
.6+|Yamaha .6+|| RT107e 
| RTX1200 
| RTX1210 
| RTX1500 
| RTX3000 
| SRT100 
.2+|Microsoft .2+|Windows Server| 2008 R2 or later 
|2012 R2 or later
.2+|Zyxel .2+|Zywall Series| 4.20 or later for statically routed Anypoint VPN connections 
|4.30 or later for dynamically routed Anypoint VPN connections
|===

[[redundant-vpn]]
== Redundant VPN

The default value for *Remote ASN* is inherited from the first VPN.
You can change this value.

////

Explanation of the difference between routing types, especially related to how they handle failover when a redundant VPN exists.


Create a redundant VPN connection to the same external network to reduce downtime if another VPN or gateway fails. Because this connection uses dynamic routing, failover will be automatic. 

Benefits of a redundant VPN
////

[[tgw-requirements]]
== Transit Gateway Attachment Requirements


* <<transit-gateway-name>>
* <<transit-gateway-region>>
* <<transit-gateway-routing>>

=== Prerequisites

Before you can add a transit gateway to CloudHub:

* Create a transit gateway on your corporate AWS account.
+
See https://docs.aws.amazon.com/vpc/latest/tgw/tgw-getting-started.html[Getting started with transit gateways^] in the AWS documentation for information about creating a transit gateway on AWS.
+
One transit gateway can support up to 10 VPC attachments.
* Purchase a Private Space offering with AWS Transit Gateway entitlements.
+
The *Transit Gateways* page is visible in Runtime Manager to Anypoint organizations that have an Anypoint VPC and VPN license.
+
Attaching one Anypoint VPC to an AWS Transit Gateway uses one Anypoint VPN license.
* Sign in to an Anypoint Platform account with either the CloudHub 2.0 Network Administrator or the CloudHub 2.0 Network Viewer user permission.
+
See https://docs.mulesoft.com/access-management/users#grant-user-permissions[Grant Permissions and Roles to Users^] (Link out from Beta docs).

* Identify the subnets in your network (in CIDR notation) that you want to make accessible through the transit gateway.

[[transit-gateway-name]]
=== Transit Gateway Name

Transit gateway attachment names can contain up to 255 alphanumeric characters (a-z, A-Z, 0-9) and hyphens (-).
Runtime Manager supports Unicode characters in private space names.

Use the same name for your transit gateway in AWS. 
You can change this name later. 

[[transit-gateway-region]]
=== Transit Gateway Region

The region corresponds to the location of your AWS Transit Gateway.

Your private space and AWS Transit Gateway must be in the same region.

[[transit-gateway-routing]]
=== Transit Gateway Routing

A maximum of 95 route table entries is permitted per VPC, regardless of the number of transit gateway attachments.
Consolidate networks to the fewest number possible to avoid exceeding the limit.

[[mulesoft-aws-account-id]]
=== MuleSoft AWS Account ID

The MuleSoft AWS account ID to use with your private space appears on the *Add Transit Gateway* page in Anypoint Platform.

This ID depends on the control plane (for example, US Cloud or EU Cloud) associated with your account.
For this reason, always use the account ID that appears in the user interface.

[[resource-share-id-owner]]
=== Resource Share ID and Owner

The resource share ID and owner appear on the *Create a resource share* page on AWS.
You use these values to verify the resource share in Anypoint Platform.

* The resource share *ID* field contains alphanumeric characters (a-z, A-Z, 0-9) and hyphens (-).
* The resource share *Owner* field contains only numbers.


== See Also 

* xref:ps-about.adoc[]
