= Troubleshoot Private Spaces  


*This topic is not needed per Valerie*

*Last update* 14-Feb-22

*NEED INPUT ON THIS TOPIC* 


== Troubleshoot VPN Connections

=== VPN Tunnel Down

=== Tunnels in a VPN Advertising Different Numbers of Routes

=== VPNs in a Connection Advertising Different Numbers of Routes

=== VPN Not Connected to Your External Network

== Troubleshoot Transit Gateway Attachments

=== MuleSoft Account Deleted from Resource Share

If the MuleSoft account is deleted from a resource share,
the transit gateway state is unknown.
The existing attachments remain available and traffic continues to flow.

To resolve this issue, on AWS, add the MuleSoft account back to the resource share.

=== Resource Share Attachments

If you get the following messages when attaching a resource share,
verify that you entered the correct resource share ID and owner:

* `We couldn’t find a matching resource share. Please review the ID and Owner and try again.`
* `This resource share is already in use by this organization or a different organization.`

=== Transit Gateway State is Unknown

If the Transit Gateway state is unknown, the resource share has probably 
been disabled or deleted.

In this case, resolve this issue on AWS.

=== Transit Gateway Attachment Deleted

If the transit gateway attachment is deleted from the AWS account,
the state is deleted.

To resolve this issue, remove the transit gateway from the private space and
recreate it.


== See Also 

