= Harden Your On-Premises Mule Runtime Engine Installation
:page-aliases: mule-runtime::hardening-your-mule-installation.adoc
:keywords: hardening, FIPS, TLS, cipher suites, keystore, BCFKS, non-root, file permissions, on-premises, on-prem, standalone

As distinct from Security, hardening refers to the steps one must perform in order to bring an application from development into production. These are elaborate procedures one must go through in order to deploy something in the IT space after you complete the development cycle.

Normally, an IT organization already has control of keeping open ports to a minimum, restricting access to administrative applications, minimizing the number of applications, and other measures to ensure quality. We recommend using secure files to configure Mule, as well as using secure configuration files.

== Follow the Hardening Checklist

To begin hardening a Mule runtime engine installation that you are hosting on-premises:

* Run Mule as a non-privileged User.
* Install Mule as a Service.
* Configure Mule to write logs or temporary files within appropriate locations. Configure logs, passwords, and keystore files.
* In some situations, you must configure usernames, passwords, and keystores on Mule. Usually, these settings are made available externally, so that DevOps can change these settings.
* Manage certificates in a keystore file.
* Use a separate property file to store usernames and passwords, and secure it using file system permissions.

For instructions specific to Runtime Fabric, see xref:runtime-fabric::configure-hardening.adoc[Hardening Mule Runtime on Runtime Fabric].

=== Run as a Non-Root User

Run on-premises Mule runtime engine as a non-root OS user. Root isn't required except to bind ports below 1024. The runtime user must own `$MULE_HOME` and have write permission to the logs directory.


On Linux and Unix, you can run Mule as any user with these caveats:

* You need write permissions to logs directory
* Without root you cannot use ports below 1024

On Windows, you need to be in admin user's group to run Mule.

== Harden in Layers

By its nature, you can situate Mule in a variety of configurations. The suggested approach to hardening involves hardening in layers beginning with the operating system, then working up the stack. The Center for Internet Security (CIS) publishes configuration benchmarks that are widely used in whole or in part as system hardening guides.

Commercial configuration management and integrity management tools can help you automate management to the CIS benchmarks. Also, Mule documentation includes a good deal of information on configuring security. If your application deals in sensitive data, consider using SSL Transport (HTTPS) to protect it.

On the network security side, security experts recommend using a good stateful inspection network firewall with a default-deny rule set and exceptions only for justified business needs. Also, any internet facing server belongs in a DMZ with strong default-deny egress rules on the firewall to prevent data exfiltration. Furthermore, you can use a network IDS/IPS to monitor and prevent known attacks. Putting the database on an internal network - not the DMZ - also helps to harden your installation.

Be sure your software developers are familiar with secure web application coding techniques. At the very least, they should be familiar with best practices to avoid common web app pitfalls, such as those listed in OWASP's top 10 Project.



== Troubleshoot Common Error Messages

=== `PKIX path building failed`

TLS trust failed while the on-premises runtime or Runtime Manager agent (`amc_setup`) connected to an HTTPS endpoint. Import the issuing CA into the JVM truststore or configure the corporate proxy certificate. This error isn't a Mule application flow failure.

== See Also

* xref:mule-runtime::securing.adoc[Security]
