
// tag::changeAppProperties[]
[[app-properties]]
= Change App Behavior with Properties

You can configure property values, such as specifying the environment or setting passwords and usernames, during app deployment.

For information about configuring app properties, see:

* xref:ch2-manage-props.adoc[] 
* xref:ch2-protect-app-props.adoc[]
// end::changeAppProperties[]



// tag::placeholders[]
[[placeholder-table]]
= Placeholders

The subdomain and path support the following optional lowercase placeholders:

`app-name`::
Resolves to the name of the app that you specified in the *Application Name* field when you deploy the app.
`business-group-id`::
Resolves to the business group ID associated with the app.
`environment-id`::
Resolves to the environment that you deploy the app to.
// end::placeholders[]

// tag::path-name-reqs[]
Paths must start and end with an alphanumeric character and can contain only alphanumeric characters, hyphens, and underscores.
// end::path-name-reqs[]

// tag::subdomain-name-reqs[]
Subdomains must start and end with an alphanumeric character and can contain only alphanumeric characters (a-z, A-Z, 0-9), hyphens (-), underscores (-), and periods (.).
// end::subdomain-name-reqs[]

// tag::appNameReqs[]
[[app-name-reqs]]
= Application Names

The application name you specify can contain between three and 59 alphanumeric characters
(a-z, A-Z, 0-9) and dashes (-).
They cannot contain spaces or other characters.

To ensure that names are unique and avoid domain conflicts, CloudHub 2.0 adds
a six-character `_uniq-id_` to the application name that you specify in the public endpoint URL.

The application name identifies your application not only in Runtime Manager but also in the public `cloudhub.io` domain.
For example, an application named `myapp` is accessible at `\http://myapp._uniq-id_._partition_.us-w2.cloudhub.io`.

To further customize your app names, you can create a naming convention.
For example, you could prepend your company name and department to all application names,
such as `mycompany-mydept-myapp`.
You can then add DNS records to hide the complex application name.
For example, you might route requests to `myapp.mycompany.com` to `mycompany-mydept-myapp._uniq-id_._partition_._region_.cloudhub.io`.
// end::appNameReqs[]


// tag::enableTLSv1[]
[[enable-tls-v1]]
= Enable TLS v1 and TLS v1.1

*REMOVE THIS CONTENT FOR GA?*

Starting with the https://docs.mulesoft.com/release-notes/cloudhub/cloudhub-runtimes-release-notes#august-3-2021[August 3, 2021 patch releases^] (Link out from Beta docs), Mule runtime engine disables TLS v1 and TLS v1.1 by default for all runtime versions.

If your app requires TLS v1 or TLS v1.1, you can enable them using JVM (Java Virtual Machine) arguments when you deploy to CloudHub 2.0:

. Click the *JVM* tab. 
. In the *Java Virtual Machine arguments* field, add one of the following arguments:
* Enable TLSv1.0 and TLSv1.1:
+
`-Drtf.allow.TLSv1.0+`
* Enable TLSv1.1:
+
`-Drtf.allow.TLSv1.1`
// end::enableTLSv1[]
