= Creating Server Groups


Create server groups to organize your hybrid standalone servers for easier management and deployment.

A server group is a set of servers that act as a single deployment target for applications so that you don’t have to deploy applications to each server individually.


== Understanding Server Groups

Deploying applications to servers in server groups provides redundancy so you can restore applications more seamlessly and quickly, with less downtime.

Unlike clusters, application instances in a server group run in isolation from the application instances running on the other servers in the group. If you experience concurrency issues with server groups, consider grouping servers in clusters.

== Before You Begin

Before creating server groups, ensure that you have:

* At least one hybrid standalone server configured
* Appropriate permissions to create and manage server groups
* Access to Runtime Manager

Additionally, review these requirements and limitations:

* All servers in a server group must be running the same versions of:
** Mule runtime engine
** Runtime Manager agent
**Java

* You can create a server group with servers with the `Running` or the `Disconnected` status, but these can’t be in the same group as servers with the `Created` status.

* You can create a server group with servers with the `Created` status.

* To add a server on which existing applications are currently running to a server group, first stop and delete the applications from the server.

== Create a Server Group

When creating a server group, you can either:

* Add the servers to Runtime Manager first and then create the server group.
* Create the group and add servers to it later.

To create a server group:

. From Anypoint Platform, select *Runtime Manager*.
. Select *Servers*.
. Click *Create Group*.
. In the *Create Server Group* page, enter the name for the server group.
+
Group names can contain between 3-40 alphanumeric characters (a-z, A-Z, 0-9) and hyphens (-). They can't start or end with a hyphen, and they can't contain spaces or other characters.
. Select the servers to include in your new server group.
. Click *Create Group*.

* The new server group appears in the *Servers* list. 
* The servers no longer appear in the *Servers* list. 

To see the list of servers in the group, select the server group name.

== Next Steps

After creating server groups, you can:

* Deploy applications to the entire group
* Configure monitoring and alerts at the group level
* Manage properties and settings across all servers in the group

== See Also

* xref:creating-servers.adoc[Creating Servers]
* xref:managing-servers-groups.adoc[Managing Server Groups]
* xref:creating-clusters.adoc[Creating Clusters]
