= Configuring Mule to Access Anypoint Platform Control Planes
:page-aliases: hyperforce::configure-mule-hyperforce.adoc, eu-control-plane::runtime-configure-eu.adoc, configuring-mule-anypoint-clouds.adoc, anypoint-clouds::configuring-mule-anypoint-clouds.adoc

Point a running Mule runtime engine (Mule) instance at the Anypoint Platform control plane that holds your organization. Mule connects to the US Cloud control plane by default. For any other control plane, set `anypoint.platform.base_uri`, `anypoint.platform.analytics_base_uri`, and the xref:access-management::managing-business-groups.adoc#client-id-and-secret[client ID and client secret] of the environment in your organization.

This is not a step in creating a Mule app. Anypoint Studio and Anypoint Code Builder do not use these properties. If you do not override the defaults, the API gateway capability of Mule is disabled in those clouds.

== When to Configure Mule

[%header%autowidth.spread]
|===
| Runtime | When to set these properties | Why

| CloudHub or CloudHub 2.0
| When you deploy the app, in the *Properties* tab in Runtime Manager, if the app must use API gateway with a non-US Cloud control plane
| You do not install Mule. MuleSoft hosts it.

| Hybrid Standalone
| When you install and register Mule, before you deploy apps onto that server
| You host Mule. Register the Runtime Manager agent with the same control plane. See xref:hybrid-standalone::setting-hybrid-standalone.adoc[Setting up Hybrid Standalone Instances].

| Runtime Fabric
| Do not use these `wrapper.conf` steps
| Use xref:runtime-fabric::install-self-managed-network-configuration.adoc[Configuring Your Network to Support Runtime Fabric].

| On-premises Mule (not registered to Runtime Manager)
| Do not set these properties
| There is no control plane. See xref:mule-runtime::mule-standalone.adoc[Run Mule Runtime Engine On-Premises].
|===

== Control Plane Endpoint Domains

Use the endpoint domain for your cloud in `anypoint.platform.base_uri` and `anypoint.platform.analytics_base_uri`. For hostnames to allowlist and for `amc_setup --region`, see xref:finding-endpoints-allowlists.adoc[Finding Endpoints and Allowlists].

[%header%autowidth.spread]
|===
| Cloud | `base_uri` | `analytics_base_uri`

| US Cloud (default)
| `https://anypoint.mulesoft.com`
| `https://analytics-ingest.anypoint.mulesoft.com`

| EU Cloud
| `https://eu1.anypoint.mulesoft.com`
| `https://analytics-ingest.eu1.anypoint.mulesoft.com`

| Canada Cloud
| `https://ca1.platform.mulesoft.com`
| `https://analytics-ingest.ca1.platform.mulesoft.com`

| Japan Cloud
| `https://jp1.platform.mulesoft.com`
| `https://analytics-ingest.jp1.platform.mulesoft.com`

| India Cloud
| `https://in1.platform.mulesoft.com`
| `https://analytics-ingest.in1.platform.mulesoft.com`

| Australia Cloud
| `https://au1.platform.mulesoft.com`
| `https://analytics-ingest.au1.platform.mulesoft.com`
|===

== Configuring a Customer-Hosted Mule Instance

For Hybrid Standalone, set these properties on the Mule instance you installed, then register the server. See xref:hybrid-standalone::creating-servers.adoc[Creating Servers].

=== Configuring Mule Properties in the Wrapper.conf File

To configure Mule in the `wrapper.conf` file, modify these properties, replacing `<n>` with an integer value that is unique within `wrapper.conf`. Use the `base_uri` and `analytics_base_uri` values for your cloud.

This example shows the `wrapper.conf` configuration for Canada Cloud:

----
wrapper.java.additional.<n>=-Danypoint.platform.client_id=<environment client ID>
wrapper.java.additional.<n>=-Danypoint.platform.client_secret=<environment client secret>
wrapper.java.additional.<n>=-Danypoint.platform.base_uri=https://ca1.platform.mulesoft.com
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.ca1.platform.mulesoft.com
----

=== Configuring Mule Properties via the Command Line

To configure Mule from the command line, pass these options when you start Mule. The `./` prefix applies only to Unix environments. Use the `base_uri` and `analytics_base_uri` values for your cloud.

This example shows the command-line configuration for EU Cloud:

----
./mule -M-Danypoint.platform.client_id=<environment client ID> -M-Danypoint.platform.client_secret=<environment client secret> -M-Danypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com -M-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

== Configuring App Properties in Runtime Manager

When you deploy to CloudHub 2.0, or to CloudHub from US Cloud or EU Cloud, include these properties in the *Properties* tab in Runtime Manager if the app must use API gateway with that control plane. Use the `base_uri` and `analytics_base_uri` values for your cloud.

This example shows the properties configuration for Japan Cloud:

----
anypoint.platform.client_id=<environment client ID>
anypoint.platform.client_secret=<environment client secret>
anypoint.platform.base_uri=https://jp1.platform.mulesoft.com
anypoint.platform.analytics_base_uri=https://analytics-ingest.jp1.platform.mulesoft.com
----

== See Also

* xref:creating-and-deploying-mule-apps.adoc[Creating and Deploying Mule Apps]
* xref:finding-endpoints-allowlists.adoc[Finding Endpoints and Allowlists]
* xref:hybrid-standalone::setting-hybrid-standalone.adoc[Setting up Hybrid Standalone Instances]
* xref:mule-runtime::runtime-installation-task.adoc[Download, Install, Configure, and Upgrade Mule]
* xref:runtime-fabric::install-self-managed-network-configuration.adoc[Configuring Your Network to Support Runtime Fabric]
