= Configuring Mule to Access Anypoint Platform Control Planes
:page-aliases: hyperforce::configure-mule-hyperforce.adoc, eu-control-plane::runtime-configure-eu.adoc, configuring-mule-anypoint-clouds.adoc, anypoint-clouds::configuring-mule-anypoint-clouds.adoc

A running Mule runtime engine (Mule) instance must know which Anypoint Platform control plane holds your organization. Mule uses that connection for API gateway and, on Hybrid Standalone, for the Runtime Manager agent. Mule connects to the US Cloud control plane by default. If your organization is in any other cloud, set `anypoint.platform.base_uri`, `anypoint.platform.analytics_base_uri`, and the xref:access-management::managing-business-groups.adoc#client-id-and-secret[client ID and client secret] of the environment.

You don't do this before you create your first Mule app. Design the app in Anypoint Studio or Anypoint Code Builder; those IDEs don't use these properties. Set them when you install and register a Hybrid Standalone instance, or when you deploy an app to CloudHub or CloudHub 2.0 that must use API gateway with a non-US Cloud control plane. If you leave the defaults, API gateway on Mule is disabled in those clouds.

== When to Configure Mule

[%header%autowidth.spread]
|===
| Runtime | When to set `anypoint.platform.base_uri` and related properties | Why

| CloudHub or CloudHub 2.0
| When you deploy the app, in the *Properties* tab in Runtime Manager, if the app must use API gateway with a non-US Cloud control plane. See <<configure-runtime-manager-properties>>.
a| MuleSoft hosts Mule in that control plane. You don't install it. Set these properties only if that app uses API gateway and your organization is not on US Cloud. Hosted Mule still defaults to US Cloud for the gateway connection.

| Hybrid Standalone
| When you install and register Mule, before you deploy apps onto that server. See <<configure-hybrid-standalone>>.
a| You host Mule. The instance cannot reach your organization until you point it at the same control plane and register the Runtime Manager agent. See xref:hybrid-standalone::setting-hybrid-standalone.adoc[Setting up Hybrid Standalone Instances].

| Runtime Fabric
| Don't set `anypoint.platform.base_uri`, `anypoint.platform.analytics_base_uri`, or the client ID and client secret on Mule
a| The fabric connects to the control plane when you install it. Configure network access for the cluster instead of setting `anypoint.platform.base_uri` on each Mule. See xref:runtime-fabric::install-self-managed-network-configuration.adoc[Configuring Your Network to Support Runtime Fabric].

| On-premises (not registered to Runtime Manager)
| Don't set `anypoint.platform.base_uri`, `anypoint.platform.analytics_base_uri`, or the client ID and client secret
a| Unregistered Mule doesn't connect to a control plane, so `anypoint.platform.base_uri` has no effect. See xref:mule-runtime::mule-standalone.adoc[Run Mule Runtime Engine On-Premises].
|===

For the `base_uri` and `analytics_base_uri` values, prefix the Anypoint Platform URL and Analytics ingest hostname for your cloud with `https://`. See xref:control-plane-hostnames-allowlists.adoc[Control Plane Hostnames and Allowlists].

[[configure-hybrid-standalone]]
== Configuring a Hybrid Standalone Instance

For Hybrid Standalone, set these properties on the Mule instance you installed, then register the server. See xref:hybrid-standalone::creating-servers.adoc[Creating Servers].

=== Configuring Mule Properties in the Wrapper.conf File

To configure Mule in the `wrapper.conf` file, modify these properties, replacing `<n>` with an integer value that is unique within `wrapper.conf`. Use `https://` plus the Platform URL and Analytics ingest hostname for your cloud.

This example shows the `wrapper.conf` configuration for Canada Cloud:

----
wrapper.java.additional.<n>=-Danypoint.platform.client_id=<environment client ID>
wrapper.java.additional.<n>=-Danypoint.platform.client_secret=<environment client secret>
wrapper.java.additional.<n>=-Danypoint.platform.base_uri=https://ca1.platform.mulesoft.com
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.ca1.platform.mulesoft.com
----

=== Configuring Mule Properties via the Command Line

To configure Mule from the command line, pass these options when you start Mule. The `./` prefix applies only to Unix environments. Use `https://` plus the Platform URL and Analytics ingest hostname for your cloud.

This example shows the command-line configuration for EU Cloud:

----
./mule -M-Danypoint.platform.client_id=<environment client ID> -M-Danypoint.platform.client_secret=<environment client secret> -M-Danypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com -M-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

[[configure-runtime-manager-properties]]
== Configuring App Properties in Runtime Manager

When you deploy to CloudHub 2.0, or to CloudHub from US Cloud or EU Cloud, include these properties in the *Properties* tab in Runtime Manager if the app must use API gateway with that control plane. Use `https://` plus the Platform URL and Analytics ingest hostname for your cloud.

This example shows the properties configuration for Japan Cloud:

----
anypoint.platform.client_id=<environment client ID>
anypoint.platform.client_secret=<environment client secret>
anypoint.platform.base_uri=https://jp1.platform.mulesoft.com
anypoint.platform.analytics_base_uri=https://analytics-ingest.jp1.platform.mulesoft.com
----

== See Also

* xref:index.adoc[Anypoint Platform Control Planes Overview]
* xref:creating-and-deploying-mule-apps.adoc[Creating and Deploying Mule Apps]
* xref:control-plane-hostnames-allowlists.adoc[Control Plane Hostnames and Allowlists]
* xref:hybrid-standalone::setting-hybrid-standalone.adoc[Setting up Hybrid Standalone Instances]
* xref:mule-runtime::runtime-installation-task.adoc[Download, Install, Configure, and Upgrade Mule]
* xref:runtime-fabric::install-self-managed-network-configuration.adoc[Configuring Your Network to Support Runtime Fabric]
