= Anypoint Platform Control Planes Overview
:page-aliases: eu-control-plane::index.adoc, eu-control-plane::object-store-eu.adoc, anypoint-clouds::index.adoc

Anypoint Platform control planes are the MuleSoft-managed environments where you design, deploy, and manage APIs and Mule apps. Each Anypoint Platform organization lives in exactly one control plane. Sign in to that control plane and deploy Mule apps to the runtime planes it supports.

For the full catalog of control planes (including MuleSoft Government Cloud and Anypoint Platform Private Cloud Edition (PCE)) and the control plane and runtime compatibility matrix, see xref:hosting-home::index.adoc[Anypoint Platform Hosting Overview].

== Control Plane Clouds

MuleSoft hosts a control plane in each supported geography and names that regional control plane a cloud, for example US Cloud or EU Cloud. US Cloud is the US control plane. EU Cloud is the EU control plane. **Cloud** is the product name of that isolated Anypoint Platform instance (login URL, organization, and data residency). **Control plane** is the management layer in that instance, as distinct from the xref:hosting-home::index.adoc#control-plane-and-runtime-plane[runtime plane], where apps run.

You choose one cloud for your organization. You do not choose a cloud and a control plane as two separate products.

Use the platform URL for the control plane that holds your organization:

[%header%autowidth.spread]
|===
| Cloud | Platform URL

| https://anypoint.mulesoft.com[US Cloud] (default)
| `anypoint.mulesoft.com`

| https://eu1.anypoint.mulesoft.com[EU Cloud]
| `eu1.anypoint.mulesoft.com`

| https://ca1.platform.mulesoft.com[Canada Cloud]
| `ca1.platform.mulesoft.com`

| https://jp1.platform.mulesoft.com[Japan Cloud]
| `jp1.platform.mulesoft.com`

| https://in1.platform.mulesoft.com[India Cloud]
| `in1.platform.mulesoft.com`

| https://au1.platform.mulesoft.com[Australia Cloud]
| `au1.platform.mulesoft.com`
|===

For data residency and compliance notes for each control plane, see xref:hosting-home::index.adoc#control-plane-hosting-options[Control Plane Hosting Options].

== Runtime Planes and Feature Availability

* Runtime plane support varies by control plane. See the xref:hosting-home::index.adoc#support-matrix-control-plane[control plane and runtime plane compatibility matrix], then xref:creating-and-deploying-mule-apps.adoc[Creating and Deploying Mule Apps].
* Object Store capabilities vary by control plane. See xref:object-store::index.adoc#os-features-control-plane[Object Store Features by Control Plane].
* MuleSoft product features vary by control plane. See xref:hyperforce::index.adoc[MuleSoft product features by control plane].

== See Also

* xref:accessing-control-planes.adoc[Accessing Anypoint Platform Control Planes]
* xref:creating-and-deploying-mule-apps.adoc[Creating and Deploying Mule Apps]
* xref:finding-endpoints-allowlists.adoc[Finding Endpoints and Allowlists]
* xref:configuring-mule-control-planes.adoc[Configuring Mule to Access Anypoint Platform Control Planes]
* xref:hosting-home::index.adoc[Anypoint Platform Hosting Overview]
* xref:hyperforce::index.adoc[Salesforce Hyperforce Overview]
