= Configuring Endpoints and Paths for Apps Deployed to a Private Space

[IMPORTANT]
CloudHub 2.0 supports customizing external endpoints only for apps that are deployed to private spaces, not shared spaces.


A private space routes requests from clients to apps deployed to the private space.

When you deploy an app to a private space, both _external_ and _internal endpoints_ are created, but you can modify only the external endpoint.
An _endpoint_ is the URL used to reach the app deployed to the private space,
for example `\https://my-app.example.com/`. External endpoints enable clients outside of the network to reach the app. Internal endpoints are accessible only within the private network, a VPN, or transit gateway (TGW). To ensure an app is accessible only within the network, you can remove external endpoints.

You can customize how requests from clients reach the app by configuring:

* Multiple custom external endpoints
+
The administrator specifies the domains that you can use for the external endpoints
by configuring the TLS context in the private space settings.
For information, see xref:ps-config-domains.adoc[].

* Different paths for the app and the external endpoint URL
+
The _path_ is the base path expected by the HTTP Listener in your app, for example `my-app.example.com/v1/api`.
+
For information, see xref:http-connector::http-listener-ref.adoc[HTTP Listener Reference - Mule 4].

You can also remove the external endpoint to ensure clients outside of the private network cannot make requests to the app.


[[before-you-begin]]
== Before You Begin

The administrator must set up the TLS contexts for the private space before you can configure the endpoints and paths for the app.

For information, see xref:ps-config-domains.adoc[].


[[configure-multiple-endpoints]]
== Configure Multiple External Endpoints

You can enable your app to be reached via multiple external endpoints, for example,
`my-app.example.com` and `my-old-app.oldname.com`.

[TIP]
To ensure that each endpoint name is unique, use the `app-name` placeholder in the subdomain,
or the path if the domain doesn't include a wildcard.

To configure multiple external endpoints:

. When deploying an app to a private space, click the *Ingress* tab.
+
See xref:ch2-deploy-private-space.adoc[].
+
If the app is already deployed:
+
--
include::partial$select-private-space.adoc[tag=selectAppsPage]
include::partial$select-private-space.adoc[tag=clickAppName]
include::partial$select-private-space.adoc[tag=clickSettings]
. Click the *Ingress* tab.
--
. Configure the first endpoint:
.. Select the first domain from the *Domain* drop-down list, for example `&#x2a;.example.com`.
+
If the domain includes a wildcard, the *Subdomain* field becomes available.
.. Enter the subdomain, or enter the `my-app` placeholder in the *Subdomain* field to use the name of the app that you specified in the *Application Name* field as the subdomain.
+
For information, see <<placeholder-table,placeholders>>.
.. Enter the path where the HTTP Listener in the app is listening, for example `v1/api`.
. If you want to configure additional endpoints, click *Add Endpoint* and repeat steps 2.1 through 2.3.
. Depending on the deployment status, choose either:
** If you're ready to deploy the application, click *Deploy*.
** If this application is deployed, click *Apply Changes*.
. Verify that the app can be reached at each configured endpoint.

// === Placeholders
include::partial$deployment.adoc[tag=placeholders,leveloffset=+2]

[[configure-different-paths]]
== Configure a Different Path for the App and the External URL Endpoint

You can configure different paths for the app and the external URL endpoint.
For example, if the app is listening on `my-app.example.com/v1/api` and you
want the app to be reachable from the internet using `my-app.example.com/api`.
When you rewrite the path URL, the new path applies to all endpoints.

To configure different paths:

. xref:ch2-deploy-private-space.adoc[Deploy the app to a private space].
. Click the *Ingress* tab.
. In the *Path* field, enter the path where you want the app to be reachable, for example, `/api`.
. In the *Path Rewrite* field, enter the base path expected by the HTTP Listener in your app, for example,  `/v1/api`.

. Click *Apply Changes* to create a new configuration for your application.

[[remove-external-endpoint]]
== Remove a External Endpoint

To remove an external endpoint:

//SELECT APP SHARED
include::partial$select-private-space.adoc[tag=selectAppsPage]
include::partial$select-private-space.adoc[tag=clickAppName]
include::partial$select-private-space.adoc[tag=clickSettings]
. Click the *Ingress* tab.
. In the endpoint link row, click *X* (*Delete*).


[[view-internal-endpoint]]
== View the Internal Endpoint for an App

An internal endpoint is accessible from inside the same private space or through
the VPN or transit gateway connection for the private space. You cannot make changes to the path or domain for an internal endpoint.

To view or copy the URL for the internal endpoint:

include::partial$select-private-space.adoc[tag=selectAppsPage]
include::partial$select-private-space.adoc[tag=clickAppName]
include::partial$select-private-space.adoc[tag=clickSettings]
. Click the *Ingress* tab.
. Hover over *internal endpoint*.
// +
// <screenshot>

== Send Application-to-Application Requests within a Private Space

In a private space, every application replica exposes an endpoint inside the private space. When you enable inbound traffic, that endpoint is exposed externally.

Every application has a DNS record in the private space internal domain. For example, the DNS record for the application `helloch2` in the `2abc2ce6-cce6-463b-afaa-a1979e3xxxxx` environment is:
```
helloch2.2abc2ce6-cce6-463b-afaa-a1979e3xxxxx.svc.cluster.local
```
Because application replicas first search DNS records in the same domain before searching the parent domain, you need only the application name to send a request to another application in the same private space. If both applications are in the same namespace, you need only the application name:
```
http://helloch2:8081/hello
```
If required, replace `http` with `https`.

== See Also

* xref:ch2-deploy-private-space.adoc[]
* xref:ps-config-domains.adoc[]
* xref:http-connector::http-listener-ref.adoc[HTTP Listener Reference - Mule 4]
