= Automatic App Restarts


CloudHub 2.0 restarts your Mule applications during infrastructure failure or maintenance, security patching, replica crashes, or replica rebalancing. 

The CloudHub 2.0 infrastructure performs a graceful shutdown by draining connections before transitioning traffic to a new instance of your application replica and terminating the older instance. If your application configuration explicitly sets the `shutdownTimeout` attribute to a value greater than two minutes and thirty seconds, the total shutdown grace period is five minutes. Otherwise, the grace period is twice the configured `shutdownTimeout` value. By default, `shutdownTimeout` is five seconds. See xref:mule-runtime::global-settings-configuration.adoc#global-configurations-reference[Global Configurations Reference].

[source,javascript,linenums]
----
<mule ...>
  <configuration shutdownTimeout="150000" /> <!-- This sets shutdownTimeout to 2 minutes, 30 seconds. Default is 5 seconds. -->
</mule>
----

To ensure business resiliency, design your application to be idempotent and deploy across multiple replicas with xref:ch2-clustering.adoc[clustering] enabled with a layer of persistence (xref:object-store::index.adoc[Object Store v2]). 

== Infrastructure Failure and Maintenance

If the compute infrastructure suffers a failure, CloudHub 2.0 moves your application to a healthy infrastructure and restarts the application replicas. Likewise, during infrastructure maintenance, the platform moves application replicas running on a compute infrastructure that becomes impaired or end-of-life onto a new infrastructure to ensure availability.

== Security Patching

To mitigate security vulnerabilities, CloudHub 2.0 patches and restarts applications every month. See the https://www.salesforce.com/content/dam/web/en_us/www/documents/legal/Agreements/versioning-back-support-policy.pdf#critical[Critical Security Vulnerabilities] policy.

== Replica Crash

If an application replica crashes for any reason, CloudHub 2.0 automatically restarts it. If it continues to fail to start, the platform attempts to restart it using an exponential backoff policy.

== Replica Rebalancing 

The CloudHub 2.0 infrastructure optimizes application efficiency through replica rebalancing. This process gracefully moves and restarts replicas, provided there are at least two replicas available. 

During rebalancing, a maximum of 30% of an application's replicas are rebalanced concurrently. The system rounds up this percentage to the number of replicas that can be disrupted. For example, if your application has two replicas, a disruption affects one replica, exceeding the configured 30%.

This table shows the potential impact of rebalancing operations on your applications based on the number of replicas.

[cols="15,20", options="header"]
|===
|Total Application Replicas
|Maximum Replicas Disrupted

|1
|1

|2
|1

|3
|1

|4
|2

|5
|2

|6
|2

|7
|3

|8
|3

|9
|3

|10
|3

|11
|4

|12
|4

|13
|4

|14
|5

|15
|5

|16
|5
|===


This method ensures that the application's configuration, including the Mule runtime version and the infrastructure, remains consistent after all restarts, except for restarts occurring after a security patching. For more details about security patching, see xref:ch2-patch-updates.adoc[].
