= Configuring Endpoints and Paths for Apps Deployed to a Private Space

*Last update* 15-June-22

[IMPORTANT]
CloudHub 2.0 supports customizing public endpoints only for apps that are deployed to private spaces, not shared spaces.


A private space routes requests from clients to apps deployed to the private space.

When you deploy an app to a private space, both _public_ and _private endpoints_ are created, but you can modify only the public endpoint.
An _endpoint_ is the URL used to reach the app deployed to the private space,
for example `\https://my-app.example.com/`. Public endpoints enable clients outside of the network to reach the app. Private endpoints ensure the app is accessible only within the private network.

You can customize how requests from clients reach the app by configuring:

* Multiple custom public endpoints
+
The administrator specifies the domains that you can use for the public endpoints
by configuring the TLS context in the private space settings.
For information, see xref:ps-config-domains.adoc[].

* Different paths for the app and the public endpoint URL
+
The _path_ is the base path expected by the HTTP Listener in your app, for example `my-app.example.com/v1/api`.
+
For information, see https://docs.mulesoft.com/http-connector/1.6/http-listener-ref[HTTP Listener Reference - Mule 4^]. (Link out from Beta docs)

You can also remove the public endpoint to ensure clients outside of the private network cannot make requests to the app.


[[before-you-begin]]
== Before You Begin

The administrator must set up the TLS contexts for the private space before you can configure the endpoints and paths for the app.

For information, see xref:ps-config-domains.adoc[].


[[configure-multiple-endpoints]]
== Configure Multiple Public Endpoints

You can enable your app to be reached via multiple public endpoints, for example,
`my-app.example.com` and `my-old-app.oldname.com`.

[TIP]
To ensure that each endpoint name is unique, use the `app-name` placeholder in the subdomain,
or the path if the domain doesn't include a wildcard.

To configure multiple public endpoints:

. When deploying an app to a private space, click the *Ingress* tab.
+
See xref:ch2-deploy-private-space.adoc[].
+
If the app is already deployed:
+
--
include::partial$select-private-space.adoc[tag=selectAppsPage]
include::partial$select-private-space.adoc[tag=clickAppName]
include::partial$select-private-space.adoc[tag=clickSettings]
. Click the *Ingress* tab.
--
. Configure the first endpoint:
.. Select the first domain from the *Domain* drop-down list, for example `&#x2a;.example.com`.
+
If the domain includes a wildcard, the *Subdomain* field becomes available.
.. Enter the subdomain, or enter the `my-app` placeholder in the *Subdomain* field to use the name of the app that you specified in the *Application Name* field as the subdomain.
+
For information, see <<placeholder-table,placeholders>>.
.. Enter the path where the HTTP Listener in the app is listening, for example `v1/api`.
. If you want to configure additional endpoints, click *Add Endpoint* and repeat steps 2.1 through 2.3.
. Depending on the deployment status, choose either:
** If you're ready to deploy the application, click *Deploy*.
** If this application is deployed, click *Apply Changes*.
. Verify that the app can be reached at each configured endpoint.

// === Placeholders
include::partial$deployment.adoc[tag=placeholders,leveloffset=+2]

[[configure-different-paths]]
== Configure a Different Path for the App and the Public Endpoint URL

You can configure different paths for the app and the public endpoint URL.
For example, the HTTP Listener in the app is listening on `my-app.example.com/v1/api` and you
want the app to be reachable from the internet using `my-app.example.com`.

To configure different paths:

. When deploying an app to a private space, click the *Ingress* tab.
+
See xref:ch2-deploy-private-space.adoc[].
+
If the app is already deployed:
+
--
include::partial$select-private-space.adoc[tag=selectAppsPage]
include::partial$select-private-space.adoc[tag=clickAppName]
include::partial$select-private-space.adoc[tag=clickSettings]
. Click the *Ingress* tab.
--
. In the *Path* field, enter the path where you want the app to be reachable, for example, `/`.
. Enable *Rewrite Request Paths* and enter the target path expected by the app, for example,  `v1/api`.
. Depending on the deployment status, choose either:
** If you're ready to deploy the application, click *Deploy*.
** If this application is deployed, click *Apply Changes*.
. Verify that the app can be reached at the new path.


[[path-rewrite-examples]]
=== Path Rewrite Examples

*_Can we get some real-world examples here?_*

[%header%autowidth.spread]
|===
|Target Path Value|Requests to... |Reach the App at...
| api | my-app.example.com | my-app.example.com/api
|===



[[remove-public-endpoint]]
== Remove a Public Endpoint

To remove a public endpoint:

//SELECT APP SHARED
include::partial$select-private-space.adoc[tag=selectAppsPage]
include::partial$select-private-space.adoc[tag=clickAppName]
include::partial$select-private-space.adoc[tag=clickSettings]
. Click the *Ingress* tab.
. In the endpoint link row, click the trash can icon (*Delete*).


[[view-private-endpoint]]
== View the Private Endpoint for an App

A private endpoint is accessible from inside the same private space or through
the VPN or transit gateway connection for the private space. You cannot make changes to the path or domain for a private endpoint.

To view or copy the URL for the private endpoint:

include::partial$select-private-space.adoc[tag=selectAppsPage]
include::partial$select-private-space.adoc[tag=clickAppName]
include::partial$select-private-space.adoc[tag=clickSettings]
. Click the *Ingress* tab.
. Hover over *private endpoint*:
+
<screenshot>

== See Also

* xref:ch2-deploy-private-space.adoc[]
* xref:ps-config-domains.adoc[]
* https://docs.mulesoft.com/http-connector/1.6/http-listener-ref[HTTP Listener Reference - Mule 4^] (Link out from Beta docs)
