= Limits in CloudHub 2.0

CloudHub 2.0 imposes the following limits:

Environments per business group:: 200

Private spaces per organization:: 100

Connections per private space:: 5. 10 if the connections are not redundant.

VPNs per private space:: 10

Transit gateway connections:: 5, depending on available network connection entitlements

HTTP header length (`maxHeaderLength`):: 32K

Firewall rules (inbound):: 180

Firewall rules (outbound):: 180

Application size:: Up to 350 MB

Application properties:: 300

Application property keys and values:: 1024 characters

Custom TLS contexts per private space:: 10

Maximum number of Client Certificates in a TLS Context:: There is no limit on the number of client certificates, but there is a limit on the store file size.
+
A TLS Context can reference one keystore and one truststore, which have their respective file size limits:
+
* Truststore maximum file size: 131072 bytes (128 KB)
* Keystore maximum file size for types JKS, JCEKS, PKCS12: 40960 bytes (40 KB).
* Keystore maximum file size for type PEM:
** Certificate File: 4096 bytes (4 KB).
** CA Path Certificate File: 28672 bytes (28 KB).

Ingress controller `content-length` in POST requests:: 0 or greater. `content-length` must be included in the POST request, even if the value is 0.





[NOTE]
Limits are subject to change.
