= Automatic App Restarts


In some scenarios, the platform can restart your Mule application. 

The CloudHub 2.0 infrastructure performs a graceful shutdown by draining connections before transitioning traffic to a new instance of your application replica and terminating the older instance. If your application configuration explicitly sets the `shutdownTimeout` attribute to a value greater than two minutes and thirty seconds, the total shutdown grace period is five minutes. Otherwise, the grace period is twice the configured `shutdownTimeout` value. By default, `shutdownTimeout` is five seconds. See xref:3.9@mule-runtime::global-settings-configuration-reference.adoc[].

[source,javascript,linenums]
----
<mule ...>
  <configuration shutdownTimeout="150000" /> <!-- This sets shutdownTimeout to 2 minutes, 30 seconds. Default is 5 seconds. -->
</mule>
----

To ensure business resiliency, design your application to be idempotent and deploy across multiple replicas with xref:ch2-clustering.adoc[clustering] enabled with a layer of persistence (xref:object-store::index.adoc[Object Store v2]). 

== Infrastructure Failure

If the compute infrastructure suffers a failure, the platform moves your application to a healthy node and restarts the application replicas to ensure availability.

== Infrastructure Maintenance

Application replicas running on compute infrastructures that become impaired or end-of-life are moved and restarted onto a new infrastructure to ensure availability.

== Security Patching

To mitigate security vulnerabilities, CloudHub 2.0 patches and restarts applications every month. See the https://www.salesforce.com/content/dam/web/en_us/www/documents/legal/Agreements/versioning-back-support-policy.pdf#critical[Critical Security Vulnerabilities] policy.

== Replica Crash

If an application replica crashes for any reason, CloudHub 2.0 automatically restarts it. If it continues to fail to start, the platform attempts to restart it using an exponential backoff policy.

== Replica Rebalancing 

CloudHub 2.0 infrastructure can perform replica rebalancing to optimize application and infrastructure efficiency. Replica rebalancing involves gracefully moving and restarting replicas. At most, 30% of replicas for an application are rebalanced concurrently. This strategy keeps the application configuration the same, including the runtime version and infrastructure.
