= CloudHub 2.0 High Availability and Disaster Recovery

CloudHub 2.0 provides high availability (HA) and disaster recovery (DR) capabilities for applications and protection against hardware failures.

CloudHub 2.0 leverages Amazon AWS for its cloud infrastructure, so availability is directly dependent on Amazon services. CloudHub 2.0 deployments and availability are region-based and correspond to Amazon regions. If an Amazon region goes down, the applications within that region are unavailable and not automatically replicated in other regions.

While the control plane is unavailable, the runtime plane continues to locally buffer log data and other telemetry data until control plane availability is restored.

CloudHub 2.0 leverages external messaging services, such as Anypoint MQ, to ensure message reliability through persistent queues. These external queues are highly available within a region, but they can‌ be inaccessible for short periods, generally seconds to minutes, during a regional outage leading to some data loss. Communication with the queues resumes after the region becomes available.

Anypoint Object Store v2 allows CloudHub 2.0 applications to store data and states across various components and applications. Object Store v2 is maintained in the same region as the deployed CloudHub 2.0 application. Data persists and becomes available after the region returns to service. However, Object Store v2 is a regional service. It doesn't provide any region failover functionality. You can't access data in Object Store v2 from an application in a different region. Implement your own external storage solution for cross-region data persistence and access. Object Store v2 doesn't provide periodic backups.

== High Availability Versus Disaster Recovery

High availability (HA) is the measure of a system’s ability to remain accessible despite a system component failure. You generally implement HA by building in multiple levels of fault tolerance or load balancing capabilities into a system. In CloudHub 2.0, you can achieve high availability by distributing multiple replicas across three Availability Zones (AZs) without requiring additional configuration.

Disaster recovery (DR) refers to the process of restoring a system to an acceptable previous state after a natural or man-made disaster, such as flooding, tornadoes, earthquakes, fires, power failures, server failures, and misconfigurations.

While they both increase overall availability, the difference is that with HA there's generally no loss of service. HA retains the service, and DR retains the data, but with DR, there's usually a slight loss of service while the DR plan executes and the system restores.

=== Key Definitions

These key terms are essential to understanding HA and DR strategies in CloudHub 2.0:

Recovery Time Objective (RTO):: This is the maximum amount of downtime a business can tolerate. The RTO represents the time it takes for the system to recover after a business disruption.

Recovery Point Objective (RPO):: This is the maximum amount of time acceptable for data loss after a disaster. The RPO influences the frequency of data backups.

== High Availability in CloudHub 2.0

CloudHub 2.0 implements high availability through several built-in mechanisms, which MuleSoft manages automatically, and require no additional configuration.

=== Redundant Locations

MuleSoft Anypoint works with instances from one place. This mechanism copies transactions in near real time across two or more availability zones in completely different, separate locations. This ensures service continuity if one location fails.

=== Regular Switching

MuleSoft regularly switches among locations for maintenance, compliance, and disaster recovery purposes. This keeps all locations up-to-date and able to handle the load if required.

=== Ingress and Egress Traffic Management

CloudHub 2.0 uses a sophisticated ingress and egress traffic management system that routes traffic optimally, even during maintenance or unexpected downtimes.

=== VPN Tunnel Updates

During VPN tunnel updates, the system sets a lower outbound multiexit discriminator (MED) value on the other tunnel. This maintains connectivity.

=== Out-of-the-Box (OOTB) High Availability

High availability is possible out-of-the-box by configuring multiple replicas across three availability zones (AZs).

== Disaster Recovery in CloudHub 2.0

Disaster recovery in CloudHub 2.0 focuses on the process of restoring systems after significant disruptions.

=== Global Distribution

You can deploy applications to CloudHub 2.0 in various global regions, including North America, South America, the European Union, and Asia-Pacific. This global distribution helps reduce latency by allowing you to host integrations closer to services.

For a list of regions where you can deploy your CloudHub 2.0 applications, see: xref:ch2-architecture.adoc#regions-and-dns-records[Runtime Plane Regions and DNS Records].

=== Regional Infrastructure

You can create your private space in a region of your choice, and the system provisions the corresponding Elastic Kubernetes Service (EKS) cluster in the private space. The us-east-1 region, for instance, has more than five availability zones, each with multiple data centers, redundant power sources, and internet connectivity.

=== Disaster Recovery Assessment

In the event of a disaster impacting an entire AWS region, MuleSoft, in conjunction with AWS, performs an assessment to determine which region has the required capacity for the affected workload.

=== Customer Responsibility for Disaster Recovery

MuleSoft manages platform HA. If your organization has significant DR requirements, build your applications accordingly and consider spreading them across multiple regions.

For more information about how to deploy for HA and DR strategies, see xref:mule-runtime::hadr-guide.adoc[High Availability and Disaster Recovery].

== Disaster Recovery Use Cases and Architecture for the Runtime Plane

CloudHub 2.0 supports various multi-region disaster recovery strategies based on application impact and statefulness. These strategies typically involve a bring-your-own (BYO) global load balancer to manage traffic distribution and failover across regions.

=== Use Case 1: Active-Active Configuration

*When to Use:* High-impact, stateless applications that require continuous availability with minimal downtime.

*Application State*:

* Set up the infrastructure with backup applications running and fully scaled up.
* Organizations using a usage-based pricing (UBP) package can enable Horizontal Pod Autoscaling (HPA) on their applications to scale dynamically in response to DR events.

*Traffic Management:*

* Use a BYO global load balancer to distribute traffic between both regions.
* Perform health checks to detect disasters.
* Traffic continues even if the control plane is down.

*Licensing:*

* For organizations using UBP, this configuration distributes messages and throughput between the two regions. It consumes flows based on the number of running replicas per application deployment.
* For organizations not using UBP, this configuration consumes additional vCores.


=== Use Case 2: Warm Standby Configuration

*When to Use:* Medium-impact stateless or stateful APIs that tolerate brief downtime during failover.

*Application State:*

* Set up the infrastructure, but scale down your applications using low vCores in the passive region.
* Scale up the applications only if you detect an outage.
* If your organization uses UBP, configure your applications with HPA where applicable.

*Traffic Management:*

* Use a BYO global load balancer to route traffic to only one region at a time.
* Perform health checks to determine DR and switch routing.
* If you configure HPA, the runtime plane continues to run even if the control plane is down.

*Licensing:*

* For organizations using UBP, this configuration doesn’t consume messages or throughput. The configuration consumes flows while the application is running, and consumes fewer flows if you configure HPA.
* For organizations not using UBP, this configuration consumes lower vCores.

*Recovery Time Objective (RTO)*

* The RTO depends on the time it takes to scale applications via HPA. HPA is available only to organizations using UBP.

=== Use Case 3: Cold Standby Configuration

*When to Use:* Low-impact, stateless, or stateful applications that tolerate longer downtime during recovery.

*Application State:*

* Set up the infrastructure, but configure your application to a stopped state in the passive region.
* Start the application only if you detect an outage.

*Traffic Management:*

* Use a BYO global load balancer to route traffic only to the region that is up.
* Use health checks to determine DR, and scripts to start your applications in backup state and switch traffic routing.
* If the control plane is down, the runtime plane DR is impacted.

*Licensing:*

* For organizations using UBP, This configuration doesn't consume flows, messages, or throughput.
* For organizations not using UBP, this configuration doesn’t consume vCores if the app is stopped.

*Recovery Time Objective (RTO):*

* The RTO depends on the time it takes to start applications via the control plane.

=== Use Case 4: Hot Standby Configuration

*When to Use:* High-impact, stateful applications that require immediate failover with minimal data loss.

*Application State:*

* Set up the infrastructure and keep the backup applications running and fully scaled up.

*Traffic Management:*

* Use a BYO global load balancer to route traffic only to one region at a time.
* Perform health checks to determine DR and flag configuration.
* Even if the control plane is down, the runtime plane continues to run.
* For non-HTTP use cases, you can externalize a DR flag and use a Groovy script to enable and disable scheduler flows.

*Licensing:*

* For organizations using UBP, this configuration doesn't consume messages or throughput. It consumes flows if the application is running.
* For organizations not using UBP, this configuration consumes additional vCores.

*Recovery Point*

* For integrating systems to resend event or data of in-flight transactions, capture recovery points in logs and monitoring.

== Runtime Plane High Availability and Disaster Recovery Summary

[%header%autowidth.spread]
|===
|API Type |Configuration
|High-Impact Stateless API | Use an active-active setup with active replicas in two regions and an external load balancer.
|High-Impact Stateful API a|
* Use a hot standby setup with applications deployed and started in both regions but processing requests only in one.
* Use an external load balancer to route traffic, and perform health checks to determine DR and switch traffic.
|Medium-Impact Stateless and Stateful API a|
* Use cold/warm standby, with applications deployed to both regions.
* Stop or scale down the applications or replicas in the secondary region.
|===

== CloudHub 2.0 High Availability and Disaster Recovery Improvements

CloudHub 2.0 Improvements over CloudHub include:

* Region and control plane decoupling from the runtime plane.
* Clustering allows you to configure HA while running the process on a single primary replica.
* Horizontal Pod Autoscaling (HPA) for warm standby optimizes usage by elastic scaling if a failover is required, even if the control plane is down.
* Active/Passive applications: Configure schedulers, listening connectors, such as MQ listener, DB listener, FTP listeners, and Salesforce listener, to be in a stopped or inactive state. 
+
Externalize DR flags and expose REST endpoints to enable and disable flows via Groovy script as needed.

== Disaster Recovery for Regional Services

Certain MuleSoft services are regional. This impacts their DR strategy.

=== Anypoint MQ

This is a regional service that runs in the same region as the application. It provides out-of-the-box (OOTB) region failover to a fallback region for standard queues. If an application's RTO tolerates processing in-flight messages only after the primary site is backed up, MQ failover is sufficient. Otherwise, configure a backup application in an Active/Passive setup, and resend in-flight events and data to the failover queue during a traffic switch. During backup with VM Queues and Anypoint MQ, data can be lost for a few minutes, depending on the configuration.

=== Object Store v2 (OSv2)

This is a regional service running in the same region as the application. OSv2 doesn't provide any region failover functionality. An application deployed in a different region can't access it. Bring your own external storage to access or backup data from different regions. OSv2 doesn't retrieve data for regular backups. Caching in ObjectStore, used for token management between calls, is region-specific, and you can't transfer it to a secondary region.

== Considerations for Disaster Recovery Implementations

Implementing a Disaster Recovery (DR) strategy for MuleSoft applications requires careful consideration of several key factors.

=== Control Plane Availability

The CloudHub 2.0 management UI and control plane are only available in the US East region of North America. You can't deploy applications while the US East region is down.

=== Caching

Use caching in ObjectStore to store the tokens among various calls. Object stores are only region-specific, and you can't transfer them to a secondary region.

=== Rate Limiting API Policies

Rate-limiting policies are currently set at the replica level. If you require rate limiting for in-flight transactions during DR, define custom policies using an external multi-region shared object store. Include a DR playbook with steps to adjust rate limits during and after DR.

=== Schedulers

Many run on a scheduled basis to read from databases or files. In this case, schedulers continue to run even if the control plane is down.

=== Listeners and Watermarks

For listeners like DB Table Row and Salesforce Events, use an external persistent store, like DB or Redis, across replicas and regions for polling and watermarks. This is crucial only if connectors use watermarks directly or indirectly.

=== Recommended Primary Runtime Region

For DR, set us-east-1 runtime plane as the primary region, and us-east-2 as the hot standby region. Even if us-east-1 is down, applications deployed in us-east-2 continue to run. Use an external load balancer to route traffic to the active region and provide transparent failover. For a warm standby scenario, use us-east-2 as the primary region, and us-east-1 as the secondary region, with an external load balancer for transparent failover.

=== IP Allowlist and Firewall Rules

There's no impact on IP allowlists and firewall rules during a hot standby DR scenario. For a warm standby scenario, update IP allowlists and firewalls as part of the DR playbook.

== Regional Differences and DR for Specific Regions

Some regions present unique challenges for multi-region DR.

=== Control Plane to Runtime Plane Ratio

* Unlike the US (1:12) and EU (1:2) regions, Canada, Japan, and India have a 1:1 control plane region to runtime plane region ratio.

=== Cross-Region Disaster Recovery Limitations

* Cross-region runtime plane DR isn't possible in Canada, Japan, and India.
* Availability Zones are typically 50 miles apart, not the 200 miles required for a true cross-region failover.

== Disaster Recovery for the Control Plane

The CloudHub 2.0 control plane's high availability and disaster recovery capabilities depend on cross-availability zone (AZ) redundancy within the same AWS region, rather than providing cross-region failover capabilities. The control plane can handle individual data center failures within a region. However, it can't automatically fail over to a different AWS region if the entire region is down.

Recovery time is up to 72 hours, with potential data loss of up to 24 hours during regional outages.

== See also

* xref:mule-runtime::hadr-guide.adoc[]
* xref:ch2-networking-guide.adoc[]
* xref:ch2-architecture.adoc[]
* xref:cloudhub::cloudhub-hadr.adoc[]
