= Limits in CloudHub 2.0

CloudHub 2.0 imposes the following limits:

Environments per business group:: 200

Private spaces per organization:: 100

Connections per private space:: 5. 10 if the connections are not redundant.

VPNs per private space:: 10

Transit gateway connections:: 5 per private space, depending on available network connection entitlements

HTTP header length (`maxHeaderLength`):: 32K

Maximum HTTP request size:: 1 GB

Maximum HTTP request timeout:: 300 seconds
+
This timeout applies to the time it takes for a client to send request data to the CloudHub 2.0 ingress load balancer (Edge). This value is not configurable and applies to both shared spaces and private spaces.
+
If the client takes longer than 300 seconds to send the complete request (for example, when uploading large files), the connection is dropped. To handle large data transfers that exceed this limit, break up the request into smaller chunks or implement asynchronous processing.
+
[NOTE]
====
Private spaces allow you to configure a separate read response timeout (the time Edge waits for the Mule application to send response data) up to 3600 seconds. For more information, see xref:ps-config-advanced.adoc#configure-http-requests-and-read-response-timeout[Configure HTTP Requests and Read-Response Timeout].
====

Maximum ingress URI size:: 4 KB

Firewall rules (inbound):: 300

Firewall rules (outbound):: 300

Application size:: Up to 350 MB

Application properties:: 300

Application property keys and values:: 1024 characters

Custom TLS contexts per private space:: 50

Maximum number of Client Certificates in a TLS Context:: There is no limit on the number of client certificates, but there is a limit on the store file size.
+
A TLS Context can reference one keystore and one truststore, which have their respective file size limits:
+
* Truststore maximum file size: 131072 bytes (128 KB)
* Keystore maximum file size for types JKS, JCEKS, PKCS12: 40960 bytes (40 KB).
* Keystore maximum file size for type PEM:
** Certificate File: 4096 bytes (4 KB).
** CA Path Certificate File: 28672 bytes (28 KB).

Ingress controller `content-length` in POST requests:: 0 or greater. `content-length` must be included in the POST request, even if the value is 0.

Anypoint Platform CloudHub 2.0 API rate limit:: 15 requests per second per remote IP address.

For information about limits in Exchange, see xref:exchange::asset-versions.adoc#asset-limits[Asset Limits].


[NOTE]
Limits are subject to change.
