= CloudHub 2.0 Overview

CloudHub 2.0 is a fully managed, containerized integration platform as a service (iPaaS) where you can deploy APIs and integrations as lightweight containers in the cloud.

== Why Deploy on CloudHub 2.0?

CloudHub 2.0:

* Supports deployments across all MuleSoft regions.
* Dynamically scales infrastructure and built-in services up or down to support elastic transaction volumes.
* Builds in security policies, protecting your services and sensitive data with encrypted secrets, firewall controls, and restricted shell access.
* Encrypts certificates, passwords, and other sensitive configuration data at rest and in transit within Anypoint Platform.
* Provides a standardized isolation boundary by running each Mule instance and service as a separate container.

For CloudHub 2.0 pricing information, contact either your account executive or your account development representative.

[[cloudhub2-hyperforce]]
== CloudHub 2.0 Features by Control Plane

All CloudHub 2.0 features are supported across all control planes, with a few exceptions that vary by deployment region:

* Deleting the default egress traffic route (0.0.0.0) can cause Anypoint Monitoring to fail in CloudHub 2.0.
* The endpoint URL format requires the region suffix or not before `cloudhub.io`.
* India Cloud uses a different Ingress controller. It maintains feature parity, but has some behavioral differences. Read this link:https://help.salesforce.com/s/articleView?id=005387259&type=1[knowledge article].

[cols="~,15,20,20,20,20"]
|===
|CloudHub 2.0 Features |US Cloud |EU Cloud |Canada Cloud |Japan Cloud |India Cloud

| Deleting the Default Route| Available | Available | Not Available | Not Available | Not Available

| Endpoints URL Format| No region suffix: `https://*.10u6w7.usa-e1.cloudhub.io`| Needs region suffix: `https://*.10u6w7.usa-e1.eu1.cloudhub.io` | Needs region suffix: `https://*.10u6w7.can-c1.ca1.cloudhub.io` | Needs region suffix: `https://*.10u6w7.jpn-e1.jp1.cloudhub.io` | Needs region suffix: `https://*.10u6w7.ind-w1.in1.cloudhub.io`
|=== 



include::partial$url-format-by-control-plane.adoc[]


== See Also

* xref:ch2-features.adoc[]
* xref:ps-create-configure.adoc[]
* xref:ps-gather-setup-info.adoc#private-network-region[Private Network Region]
