= Assigning Permissions


Before you set up your private space, ensure you have the required permissions
assigned to your user account or a team to which you belong.
To assign permissions, you need access to Access Management and the Organization Administrator permission.

* To set up and manage a private space, you need the CloudHub Network Administrator permission.
* To view a private space, you need the CloudHub Network Viewer permission.
** To view the schedules in applications deployed to CloudHub 2.0 and Runtime Fabric, you need to assign the Exchange Viewer permission to the Business Organization that owns the asset.
* To deploy applications from Exchange, you need to assign the Exchange Contributor and Exchange Viewer permissions to the Business Organization that owns the asset.
* To deploy applications in Runtime Manager, you need the Create Applications permission.
* To view all applications on the *Applications* page in Runtime Manager, you need the Read Applications and CloudHub Network Viewer permission.
* Assigning the *Create Applications* role to a user also gives the *Read Applications* role that is required to deploy applications.

Depending on your organization's permission structure, you can assign these permissions using the xref:access-management::teams.adoc[Teams] feature, the xref:access-management::users.adoc#grant-user-permissions[Roles] feature (deprecated), or by assigning an xref:access-management::users.adoc#grant-user-permissions[individual user permission].

Note that users who have the Organization Administrator permission can also view and manage all private spaces and additional privileges across Anypoint Platform. However, you should not assign this permission as a substitute for CloudHub 2.0-specific privileges. For more information, see xref:access-management::permissions-by-product.adoc[general permissions].


== See Also

* xref:access-management::index.adoc[]
