= Configure SSL Endpoints and Certificates

While you do not have to manage load balancers manually in CloudHub 2.0, each private space must have at least one certificate associated with it. To configure an SSL endpoint for your load balancer to serve to clients, provide a certificate and private key pair for your load balancer.

A load balancer can have multiple and independent SSL endpoints, each identified by its server certificate common name.

== Before You Begin

To associate an SSL endpoint, you must provide:

* An encrypted, PEM-encoded (Privacy-Enhanced Mail) certificate file.
* A second file containing the private key of your PEM certificate.

[[pem]]
== Create a Certificate File and Private Key with the openssl Command

You can create both an encrypted, PEM-encoded certificate file and a private key using `openssl`.

For example, to create a self-signed certificate and corresponding private key:

. Enter:
+
----
openssl req -newkey rsa:2048 -keyout example-com-private-key.pem -x509 -days 3000 -out example-com-crt.pem -passout pass:examplePassword
----
. When prompted, enter the certificate information.
+
This command creates two `.pem` files:
+
----
example-com-crt.pem
example-com-private.pem
----
+
You upload these `.pem` files in Runtime Manager or pass them on the command line when you add an SSL endpoint to the load balancer.

Alternatively, you can pass a certificate information configuration file to the `openssl` command using the `-config` option.

For example, this certificate configuration file named `example-com.cfg` defines the DNS domain `example.com` that includes some SANs (Subject Alternate Names) for Mule applications `app1.example.com` and `app2.example.com`.

----
[ req ]
default_bits       = 2048
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt = no
[ req_distinguished_name ]
countryName                 = US
stateOrProvinceName         = California
localityName               = San Francisco
organizationName           = MuleSoft
commonName                 = example.com

[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1   = app1.example.com
DNS.2   = app2.example.com
----

Run the following command:

----
openssl req -newkey rsa:2048 -nodes -keyout example-com-private.pem -x509 -days 3000 -out example-com-crt.pem -config example-com.cfg
----


=== Create a Wildcard Certificate

You might want to create a wildcard certificate to support subdomain requests, for example, to support `example.com` and include `app1.example.com` and `app2.example.com`, as well as any future subdomain names.

To create a wildcard certificate that maps any subdomain name to `example.com`:

. Create a file that includes this configuration:
+
----
[ req ]
default_bits       = 2048
distinguished_name = req_distinguished_name
prompt = no
[ req_distinguished_name ]
countryName                 = US
stateOrProvinceName         = California
localityName               = San Francisco
organizationName           = MuleSoft
commonName                 = *.example.com
----

. Pass the certificate configuration file in an `openssl` command:
+
----
openssl req -newkey rsa:2048 -nodes -keyout example-com-private.pem -x509 -days 3000 -out example-com-crt.pem -config example-com.cfg
----

. Decrypt the private key using `openssl`:
+
----
openssl rsa -in example-com-private.pem -out example-com-private-decrypted.pem
----

[[keystore]]
== Create a Keystore and Import a Certificate

A keystore is a server-side repository that stores private keys and certificates. A truststore is a client-side repository of certificates that the client trusts.

=== Prerequisites

* JDK must be installed on the system.
* The `keytool` utility is available in the `JAVA_HOME/bin` directory.

=== Create a Keystore

To create a keystore that stores your private key and certificate:

----
keytool -v -genkeypair -keyalg RSA \
  -dname "cn=MuleSoft, ou=MuleSoft, o=MuleSoft, L=San Francisco, st=CA, c=US" \
  -ext SAN="DNS:localhost,IP:127.0.0.1" \
  -validity 1825 \
  -alias mykeyalias \
  -keystore keystore.jks \
  -keypass mule123 \
  -storepass mule123
----

The following table describes the command parameters:

[%header,cols="1,3"]
|===
|Parameter |Description

|`-v`
|Verbose output

|`-genkeypair`
|Generates a key pair (public and private key)

|`-keyalg RSA`
|Uses RSA algorithm for key generation

|`-dname`
|Distinguished name with certificate details

|`-ext SAN`
|Subject Alternative Name extension (DNS and IP)

|`-validity 1825`
|Certificate validity in days (5 years)

|`-alias`
|Alias name for the key entry

|`-keystore`
|Path to the keystore file

|`-keypass`
|Password for the private key

|`-storepass`
|Password for the keystore
|===

=== Export a Certificate from the Keystore

To export a certificate so you can add it to a truststore or share it:

----
keytool -export -alias mykeyalias -file localhost.cer -keystore keystore.jks
----

NOTE: You are prompted to enter the keystore password.

=== Create a Truststore

To create a truststore and import a certificate:

----
keytool -import -v -trustcacerts -alias mykeyalias -file localhost.cer -keystore truststore.jks
----

The following table describes the command parameters:

[%header,cols="1,3"]
|===
|Parameter |Description

|`-import`
|Imports the certificate

|`-v`
|Verbose output

|`-trustcacerts`
|Considers the certificate as trusted

|`-alias`
|Alias for the certificate in truststore

|`-file`
|The certificate file to import

|`-keystore`
|Path to the truststore file
|===

=== Import an Existing Certificate into a Keystore

To import an existing certificate into a keystore:

----
keytool -importcert -file <certificate_name.cer> -keystore <keystore_path> -alias "<certificate_name>"
----

Replace the placeholders:

* `<certificate_name.cer>` - The certificate file to import
* `<keystore_path>` - Path to your keystore file
* `<certificate_name>` - Alias for the imported certificate

=== Common Keytool Commands

The following table lists commonly used keytool commands:

[%header,cols="2,3"]
|===
|Command |Description

|`keytool -list -keystore keystore.jks`
|List all entries in a keystore

|`keytool -list -v -keystore keystore.jks`
|List entries with details

|`keytool -delete -alias myalias -keystore keystore.jks`
|Delete an entry from keystore

|`keytool -storepasswd -keystore keystore.jks`
|Change keystore password

|`keytool -keypasswd -alias myalias -keystore keystore.jks`
|Change key password
|===

CAUTION: Keep your keystore and truststore passwords secure. Store keystores in a secure location with restricted access, regularly rotate certificates before they expire, and back up your keystores in a secure manner.

== Configure Certificates for Production

Typically, in a production environment, your certificate is signed by a valid Certificate Authority (CA).
Each SSL endpoint can have multiple CA certificates and CRLs (Certificate Revocation Lists). You must provide each of these certificates in a single encrypted, PEM-encoded file. Ordering is not important for independent CA certificates, but certificates in a chain of trust must be concatenated.
