= Configure SSL Endpoints and Certificates

While you do not have to manage load balancers manually in CloudHub 2.0, each private space must have at least one certificate associated with it. To configure an SSL endpoint for your load balancer to serve to clients, provide a certificate and private key pair for your load balancer.

A load balancer can have multiple and independent SSL endpoints, each identified by its server certificate common name.

== Before You Begin

To associate an SSL endpoint, you must provide:

* An encrypted, PEM-encoded (Privacy-Enhanced Mail) certificate file.
* A second file containing the private key of your PEM certificate.

[[pem]]
== Create a Certificate File and Private Key with the openssl Command

You can create both an encrypted, PEM-encoded certificate file and a private key using `openssl`.

For example, to create a self-signed certificate and corresponding private key:

. Enter:
+
----
openssl req -newkey rsa:2048 -keyout example-com-private-key.pem -x509 -days 3000 -out example-com-crt.pem -passout pass:examplePassword
----
. When prompted, enter the certificate information.
+
This command creates two `.pem` files:
+
----
example-com-crt.pem
example-com-private.pem
----
+
You upload these `.pem` files in Runtime Manager or pass them on the command line when you add an SSL endpoint to the load balancer.

Alternatively, you can pass a certificate information configuration file to the `openssl` command using the `-config` option.

For example, this certificate configuration file named `example-com.cfg` defines the DNS domain `example.com` that includes some SANs (Subject Alternate Names) for Mule applications `app1.example.com` and `app2.example.com`.

----
[ req ]
default_bits       = 2048
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt = no
[ req_distinguished_name ]
countryName                 = US
stateOrProvinceName         = California
localityName               = San Francisco
organizationName           = MuleSoft
commonName                 = example.com

[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1   = app1.example.com
DNS.2   = app2.example.com
----

Run the following command:

----
openssl req -newkey rsa:2048 -nodes -keyout example-com-private.pem -x509 -days 3000 -out example-com-crt.pem -config example-com.cfg
----


=== Create a Wildcard Certificate

You might want to create a wildcard certificate to support subdomain requests, for example, to support `example.com` and include `app1.example.com` and `app2.example.com`, as well as any future subdomain names.

To create a wildcard certificate that maps any subdomain name to `example.com`:

. Create a file that includes this configuration:
+
----
[ req ]
default_bits       = 2048
distinguished_name = req_distinguished_name
prompt = no
[ req_distinguished_name ]
countryName                 = US
stateOrProvinceName         = California
localityName               = San Francisco
organizationName           = MuleSoft
commonName                 = *.example.com
----

. Pass the certificate configuration file in an `openssl` command:
+
----
openssl req -newkey rsa:2048 -nodes -keyout example-com-private.pem -x509 -days 3000 -out example-com-crt.pem -config example-com.cfg
----

. Decrypt the private key using `openssl`:
+
----
openssl rsa -in example-com-private.pem -out example-com-private-decrypted.pem
----

[[keystore]]
== Create a Keystore and Import a Certificate

A keystore is a server-side repository that stores private keys and certificates. A truststore is a client-side repository of certificates that the client trusts.

Use the Java `keytool` command-line utility to create and manage keystores. Run these commands in a terminal or command prompt.

=== Before You Begin

* Install the JDK on your system.
* Locate the `keytool` utility in the `JAVA_HOME/bin` directory.

=== Create a Keystore

To create a keystore that stores your private key and certificate:

----
keytool -v -genkeypair -keyalg RSA \
  -dname "cn=MuleSoft, ou=MuleSoft, o=MuleSoft, L=San Francisco, st=CA, c=US" \
  -ext SAN="DNS:localhost,IP:127.0.0.1" \
  -validity 1825 \
  -alias mykeyalias \
  -keystore keystore.jks \
  -keypass mule123 \
  -storepass mule123
----

[%header%autowidth.spread]
|===
|Parameter |Description

|`-v`
|Enables verbose output

|`-genkeypair`
|Generates a key pair (public and private key)

|`-keyalg RSA`
|Uses RSA algorithm for key generation

|`-dname`
|Specifies the distinguished name with certificate details

|`-ext SAN`
|Adds Subject Alternative Name extension (DNS and IP)

|`-validity 1825`
|Sets certificate validity in days (5 years)

|`-alias`
|Sets the alias name for the key entry

|`-keystore`
|Specifies the path to the keystore file

|`-keypass`
|Sets the password for the private key

|`-storepass`
|Sets the password for the keystore
|===

=== Export a Certificate from the Keystore

To export a certificate so you can add it to a truststore or share it:

----
keytool -export -alias mykeyalias -file localhost.cer -keystore keystore.jks
----

[NOTE] 
Enter the keystore password when prompted.

=== Create a Truststore

To create a truststore and import a certificate:

----
keytool -import -v -trustcacerts -alias mykeyalias -file localhost.cer -keystore truststore.jks
----

[%header%autowidth.spread]
|===
|Parameter |Description

|`-import`
|Imports the certificate

|`-v`
|Enables verbose output

|`-trustcacerts`
|Marks the certificate as trusted

|`-alias`
|Sets the alias for the certificate in the truststore

|`-file`
|Specifies the certificate file to import

|`-keystore`
|Specifies the path to the truststore file
|===

=== Import an Existing Certificate into a Keystore

To import an existing certificate into a keystore:

----
keytool -importcert -file <certificate_name.cer> -keystore <keystore_path> -alias "<certificate_name>"
----

Replace the placeholders:

* `<certificate_name.cer>` - The certificate file to import
* `<keystore_path>` - Path to your keystore file
* `<certificate_name>` - Alias for the imported certificate

=== Common Keytool Commands

[%header%autowidth.spread]
|===
|Command |Description

|`keytool -list -keystore keystore.jks`
|Lists all entries in a keystore

|`keytool -list -v -keystore keystore.jks`
|Lists entries with details

|`keytool -delete -alias myalias -keystore keystore.jks`
|Deletes an entry from the keystore

|`keytool -storepasswd -keystore keystore.jks`
|Changes the keystore password

|`keytool -keypasswd -alias myalias -keystore keystore.jks`
|Changes the key password
|===

CAUTION: Keep your keystore and truststore passwords secure. Store keystores in a secure location with restricted access, regularly rotate certificates before they expire, and back up your keystores in a secure manner.

== Configure Certificates for Production

Typically, in a production environment, your certificate is signed by a valid Certificate Authority (CA).
Each SSL endpoint can have multiple CA certificates and CRLs (Certificate Revocation Lists). You must provide each of these certificates in a single encrypted, PEM-encoded file. Ordering is not important for independent CA certificates, but certificates in a chain of trust must be concatenated.
