= Gathering Required Setup Information
:page-aliases: network-admin-guide.adoc

Use the following sections to gather the information you'll need to set up your private space.
For information about private spaces, see xref:ch2-private-space-about.adoc[].

You might need to collaborate with your network administrator if you don't have access to this information.
In this case, share this setup checklist with them.

[[organization-limits]]
== Organization Entitlements and CloudHub 2.0

include::partial$include-enforcement.adoc[]

[[setup-info-private-space]]
== Information Required to Set Up a Private Space

The following list summarizes the information required to set up a private space.
For details about each requirement, see the sections that follow.

*Private Network Setup*::
+
--
* <<private-space-name,Private space name>>
* <<private-network-region,Private network region>>
* <<cidr-block,CIDR block>>
* <<internal-dns-server,Internal DNS servers>> (optional)

** <<server-ip-addresses,IP addresses>>
** <<domains>>
--

*VPN Connection Type*::
+
--
* <<vpn-name, VPN name>>
* <<remote-ip-address,Remote IP>>
* *<<dynamic-vpn-routing,Dynamic Routing Type>>*

** <<local-asn>>
** <<remote-asn>>
* *<<static-vpn-routing,Static Routing Type>>*
** <<Local ASN>> (_first VPN only_)
** <<static-ip-prefixes,Static IP prefixes>>
* *<<advanced-tunnel-configuration,Advanced Tunnel Configuration>>* (_optional_)

** Tunnel 1

*** <<inside-ip-cidrs,Inside IP CIDRs>>
*** <<preshared-keys,Pre-shared keys>>
** Tunnel 2
*** <<inside-ip-cidrs,Inside IP CIDRs>>
*** <<preshared-keys,Pre-shared keys>>
** <<auto-tunnel-initiation,Automatic Tunnel Initiation>> (_first VPN only_)

* <<supported-gateway-devices,*Supported Gateway Devices*>>
** Device vendor
** Device platform
** Device software
--


*Redundant VPN Connection* (_optional_)::
+
--
* *<<dynamic-vpn-routing,Dynamic Routing Type>>*

** <<remote-ip-address,Remote IP>>
** <<remote-asn>>

* *<<static-vpn-routing,Static Routing Type>>*

** <<static-ip-prefixes,Static IP prefixes>>
* *<<advanced-tunnel-configuration,Advanced Tunnel Configuration>>* (_optional_)

** Tunnel 1

*** <<inside-ip-cidrs,Inside IP CIDRs>>
*** <<preshared-keys,Pre-shared keys>>
** Tunnel 2
*** <<inside-ip-cidrs,Inside IP CIDRs>>
*** <<preshared-keys,Pre-shared keys>>

* <<supported-gateway-devices,*Supported Gateway Devices*>>
** Device vendor
** Device platform
** Device software
--

*Transit Gateway Attachment Connection Type*::
+
--
* <<transit-gateway-name,Transit gateway name>>
* <<transit-gateway-region,Transit gateway region>>
* <<transit-gateway-routing,Transit gateway routing>>
* <<mulesoft-aws-account-id,MuleSoft AWS account ID>>
* <<resource-share-id-owner,Resource share ID>>
* <<resource-share-id-owner,Resource share owner>>
--


[[private-network-requirements]]
== Private Network Requirements

* <<private-space-name>>
* <<private-network-region>>
* <<cidr-block>>
* <<connection-type>>
* <<internal-dns-server>>

[[private-space-name]]
=== Private Space Name

Private space names can contain between 1 and 36 alphanumeric characters (a-z, A-Z, 0-9) and hyphens (-).
Runtime Manager supports Unicode characters in private space names.

The private space name appears in the list when you select a deployment target for your apps.

You cannot rename a private space.

[[private-network-region]]
=== Private Network Region

The _region_ is the Amazon region to deploy your apps to, such as `usa-e1`.

The complete list of supported regions is:

----
US East (Northern Virginia)
US East (Ohio)
US West (Northern California)
US West (Oregon)
Canada (Central)
South America (Sao Paulo)
Europe (Ireland)
Europe (Frankfurt)
Europe (London)
Asia Pacific (Singapore)
Asia Pacific (Sydney)
Asia Pacific (Tokyo)
----

// CIDR Block Shared
[[cidr-block]]
include::partial$create-config.adoc[tag=cidrBlock,leveloffset=+2]


[[internal-dns-server]]
=== Internal DNS Servers (Optional)

If your corporate network uses internal DNS servers to resolve requests to
custom domains, you must configure those servers to enable apps deployed
to a private space to access internal resources that are not reachable
from the public internet.

To configure internal DNS servers, specify the IP addresses for your internal
domain servers and the domains that you want to be resolved by internal DNS.

The private space resolves the domains using the specified DNS server,
enabling you to use internal host names in your private network
as long as your applications use the FQDN to request back-end resources.

[[server-ip-addresses]]
==== Server IP Addresses

The _Server IP addresses_ identify the internal DNS servers that resolve requests
to custom domains.

To provide redundancy, you can configure multiple internal DNS servers.

When configuring the IP addresses for the DNS servers, keep the following in mind:

* You configure DNS servers within a private space, so the server IP addresses you configure must be reachable from the private space.
+
If the server isn't reachable, DNS resolution fails.
* If you configure multiple servers, the private space queries any DNS server in the list for the specified domains at any time, in any order.
* All name servers must present the same DNS record.
* After the private space receives a valid response from any configured name server, it doesn't retry the request.
+
If one of the name servers doesn't have a record for the domain,
it returns the response `NXDOMAIN` (non-existent domain).
Because this response is valid, the private space doesn't send the query
to the other servers.

[[domains]]
==== Domains

_Domains_ identify the internal domains that must be accessible from the private space.
The configured internal DNS servers resolve the specified domains, and the
external DNS server resolves all other domains.

To configure an internal domain, specify the IP address.

The following internal private DNS domains are not supported:

* `cloudhub.io`
* `mulesoft.com`
* `anypointdns.net`
* `amazon.com`
* `amazonaws.com`
* `compute.internal`
* `io`
* `com`
* `net`
* `internal`
* `local/domain.com`

// To specify an internal domain, use the second-level domain name, such as `mulesoft.com`.

[NOTE]
The total number of characters for all configured domains is 229.

[[connection-type]]
=== Connection Type

* <<vpn-requirements,Virtual Private Network (VPN)>>
* <<tgw-requirements,Transit Gateway Attachment>>

[[vpn-requirements]]
== VPN Requirements

Review the recommendations and limitations in xref:ps-vpn-about.adoc[].

* <<vpn-name>>
* <<remote-ip-address>>
* <<dynamic-vpn-routing>>
* <<static-vpn-routing>>
* <<local-asn>>
* <<remote-asn>> (dynamic routing only)
* <<static-ip-prefixes>> (static routing only)
* <<inside-ip-cidrs>> (advanced tunnel configuration only)
* <<preshared-keys>> (advanced tunnel configuration only)
* <<auto-tunnel-initiation>> (advanced tunnel configuration only)
* <<supported-gateway-devices>>

[NOTE]
include::partial$create-config.adoc[tag=consolidateNetworks]


[[vpn-name]]
=== VPN Name

The _VPN name_ is the name of the VPN connection.


[[remote-ip-address]]
=== Remote IP Address

The _remote IP address_ is the public (single, static) IP address of your VPN endpoint.

[[dynamic-vpn-routing]]
=== Dynamic VPN Routing (BGP)

For dynamic routing, your device uses Border Gateway Protocol (BGP) to advertise routes to Anypoint VPN.
If your device supports BGP, you can select dynamic routing; otherwise, select static routing.

To create a dynamic VPN connection, in addition to the static VPN connection requirements, your VPN device must be able to:

* Establish BGP peering
* Support route-based VPNs (bind tunnels to logical interfaces)
* For IPsec, enable perfect forward secrecy (PFS) with the Diffie-Hellman Phase 2 groups 2, 5, 14-24.

////
Dynamic (BGP) Routing Type option should link to an explanation of the difference between routing types, especially related to how they handle failover when a redundant VPN exists.
////

[[static-vpn-routing]]
=== Static VPN Routing

If your gateway device doesn't support BGP, you must use static routing.
You might also want to use static routing if you want to provide your own secrets.
// or set the PTP (Precision Time Protocol) CIDRs for the network interfaces on your router.

Static routing requires you to specify the routes (subnets) in your network that are accessible through Anypoint VPN.

To create a static VPN connection, your VPN endpoint must be able to:

* Establish IKE Security Associations using a Pre-Shared Key (PSK)
* Establish IPsec Security Associations in Tunnel mode
* Use any combination of IPsec settings that Anypoint Platform supports
* Fragment IP packets before encryption
+
You must fragment packets that are too large to transmit.
+
Your gateway device must be able to fragment packets before encapsulation.
* Use one Security Association (SA) pair per tunnel
+
Anypoint VPN supports one unique SA pair (one inbound and one outbound connection) per tunnel.
Some policy-based devices create an SA for each ACL (access-control list) entry.
In this situation, you must consolidate your rules and then filter unwanted traffic.
* Use IPsec Dead Peer Detection (DPD)
+
DPD allows devices to rapidly identify when network conditions change.
You can enable DPD on the Anypoint Platform endpoint using `DPD Interval: 10` and `DPD Retries: 3`.
* Allow asymmetric routing
+
Asymmetric routing occurs when routing policies send traffic from your network to the private space through one tunnel and traffic returns from the private space through the other tunnel.
The Anypoint Platform VPN endpoint selects the tunnel using an internal algorithm, making the return path dynamic.
If your device uses an active/active tunnel configuration, you must allow asymmetric routing for each Anypoint VPN connection.
* For IPsec, enable perfect forward secrecy (PFS) with the Diffie-Hellman Phase 2 groups 2, 5, 14-24.

[[local-asn]]
=== Local ASN

The _local ASN_ (Autonomous System Number) specifies a private ASN (`64512–65534`) to assign to the Anypoint Platform side of the VPN.

Use a private ASN that is not already assigned to your network.
The default value is `64512`.

[NOTE]
You configure the local ASN for both static and dynamic routing.

include::partial$caveats.adoc[tag=localAsnNote]
For subsequent VPNs that you create in the private space,
the *Local ASN* option is not available for static routing.

To change the local ASN after creating the VPN,
you must delete all existing connections first.

////
Local ASN is a property of the VPN gateway, which is used for all VPNs in a private space and must be created with its first VPN. The only opportunity to set the Local ASN is when the VPN gateway is created.

However, to answer your second question, Michelle said that users can set a different Local ASN when creating a VPN if they delete all existing connections first, presumably because we'll create a new VPN gateway at that point.
////

[[remote-asn]]
=== Remote ASN

The _remote ASN_ specifies a private ASN that corresponds to your backend.

[NOTE]
You configure the remote ASN only for dynamic routing.

Use either an existing ASN assigned to your network or a private ASN (`64512–65534`) that is not
already assigned to your network.
The default value is `65001`.

[[static-ip-prefixes]]
=== Static IP Prefixes

The _static IP prefixes_ are IP prefixes to advertise to your private network in Anypoint Platform,
in CIDR notation.

[NOTE]
You configure the static IP prefixes only for static routing.

A maximum of 95 route table entries is allowed per private network,
regardless of the number of VPN connections.
To avoid exceeding the limit, consolidate networks to the fewest number possible.

[[advanced-tunnel-configuration]]
=== Advanced Tunnel Configuration (Optional)

You can customize the tunnel configuration if you want to specify
custom values for inside IP CIDRs and pre-shared keys, or if you want to
disable automatic tunnel initiation.

Any values that you don't specify are set to the default.

[[inside-ip-cidrs]]
==== Inside IP CIDRs

The _inside IP CIDRs_ is the IP address range for the internal address of the VPN tunnel.

[NOTE]
You specify the inside IP CIDRs only for custom tunnel configuration.
For automatic tunnel configuration, these values are auto-generated.

For each tunnel, enter the IP address range for the internal address of the VPN tunnel.

You can specify a size /30 CIDR block from the `169.254.0.0/16` range.
The CIDR block must be unique across all private network connections. 

MuleSoft recommends using subnets from standard RFC 1918 addresses, such as `10.0.0.0/8`, `172.16.0.0/12`, and `192.168.0.0/16`.

[[reserved-cidr]]
==== Reserved Corporate CIDR

Optionally, when you create your private space and configure your private network, you can configure _reserved CIDR blocks_ that correspond with your reserved corporate network CIDRs. When you reserve CIDRs in private network configuration, Anypoint Platform does not use the blocks you specify when associating IP addresses with your private space. This prevents overlap between your corporate network CIDRs and Anypoint Platform infrastructure. 

There are two strategies for reserving CIDRs during private space creation:

. Provide all reserved corporate CIDRs
+
Specify all CIDR blocks you plan to use within your corporate network. CloudHub 2.0 automatically checks for conflicts with its CIDR pool and chooses options that do not overlap. +
This approach simplifies setup but requires providing a potentially larger list.
+
. Manually identify overlapping corporate CIDRs
+
Manually review the MuleSoft CIDR pool. Then, specify only the CIDRs from your corporate network CIDR list that conflict with options in the MuleSoft CIDR pool. This approach minimizes the list you provide, but you must check for overlap beforehand. +
Note that the MuleSoft CIDR pool is subject to change.

[[unusable-cidr]]
==== Unusable CIDR

You cannot use the following list of CIDR blocks:

----
169.254.0.0/30
169.254.1.0/30
169.254.2.0/30
169.254.3.0/30
169.254.4.0/30
169.254.5.0/30
169.254.169.252/30
----

Anypoint Platform has a list of CIDRs as an internal CIDR pool for provisioning private space networks. The MuleSoft CIDR pool is subject to change. You can configure the following as reserved CIDR blocks, but you cannot use them as private space network CIDRs:

----
100.64.0.0/16
100.66.0.0/16
100.67.0.0/16
100.68.0.0/16
----

// Additionally, AWS EKS uses `10.100.0.0/16` or `172.20.0.0/16` inside of private space networks. 

[[preshared-keys]]
==== Pre-shared Keys

A _pre-shared key_ (PSK) is a shared secret that was previously shared between
two ends of a connection for the VPN tunnels.

[NOTE]
You specify the PSK only for custom tunnel configuration.
For automatic tunnel configuration, these values are auto-generated.

For static connections, your VPN endpoint uses pre-shared keys (PSKs) to establish IKE Security Associations.

For each tunnel, enter a value of between 8-64 characters that does not begin with zero (0).
Use only alphanumeric characters, periods (.), and underscores (&#95;).


[[auto-tunnel-initiation]]
==== Automatic Tunnel Initiation

By default, VPN tunnels are initiated automatically.

If you deselect this option, you must generate traffic from the customer gateway
to establish VPN tunnels.

This setting applies to all VPNs in the connection and the option isn't available for subsequent redundant VPNs.

[NOTE]
Modifying the tunnel initiation after VPN creation causes all VPNs in this connection to restart.

[[supported-gateway-devices]]
=== Supported Gateway Devices

A _gateway device_ is a physical or software appliance on your organization's side of the VPN connection.

Your network administrator must configure the device to work with the Anypoint VPN connection.

The following gateway network devices are known to work with Anypoint VPN.
If your device does not appear in the list of tested devices,
check the requirements to verify that your device is suitable for use with Anypoint VPN.
See <<dynamic-vpn-routing>> and <<static-vpn-routing>>.

[%header%autowidth.spread]
.Supported Gateway Devices
|===
|Device Vendor | Device Platform | Device Software
|Check Point | Security Gateway | R77.10 or later
.2+|Cisco | ASA | ASA 8.2 or later
|IOS | Cisco IOS 12.4 or later
|Dell | SonicWALL | SonicOS 5.9 or later
|Fortinet | Fortigate 40+ Series | FortiOS 4.0 or later
.4+|Juniper | J-Series Service Router | JunOS 9.5 or later
| SRX-Series Services Gateway | JunOS 11.0 or later
| SSG | ScreenOS 6.1 or 6.2 or later
| ISG | ScreenOS 6.1 or 6.2 or later
|Netgate | pfSense | OS 2.2.5 or later
|Palo Alto Networks || PANOS 4.1.2 or later
.6+|Yamaha .6+|| RT107e
| RTX1200
| RTX1210
| RTX1500
| RTX3000
| SRT100
.2+|Microsoft .2+|Windows Server| 2008 R2 or later
|2012 R2 or later
.2+|Zyxel .2+|Zywall Series| 4.20 or later for statically routed Anypoint VPN connections
|4.30 or later for dynamically routed Anypoint VPN connections
|===

[[redundant-vpn]]
== Redundant VPN

The default value for *Remote ASN* is inherited from the first VPN.
You can change this value.


[[tgw-requirements]]
== Transit Gateway Attachment Requirements

* <<transit-gateway-name>>
* <<transit-gateway-region>>
* <<transit-gateway-routing>>

[NOTE]
include::partial$create-config.adoc[tag=consolidateNetworks]

=== Before You Begin

Before you can add a transit gateway to CloudHub:

* Create a transit gateway on your corporate AWS account.
+
See https://docs.aws.amazon.com/vpc/latest/tgw/tgw-getting-started.html[Getting started with transit gateways^] in the AWS documentation for information about creating a transit gateway on AWS.
+
One transit gateway can support up to 10 VPC attachments.
* Purchase a Private Space offering with AWS Transit Gateway entitlements.
+
The *Transit Gateways* page is visible in Runtime Manager to Anypoint organizations that have an Anypoint VPC and VPN license.
+
Attaching one Anypoint VPC to an AWS Transit Gateway uses one Anypoint VPN license.
* Sign in to an Anypoint Platform account with either the CloudHub 2.0 Network Administrator or the CloudHub 2.0 Network Viewer user permission.
+
See xref:access-management::users.adoc#grant-user-permissions[Grant Permissions and Roles to Users].

* Identify the subnets in your network (in CIDR notation) that you want to make accessible through the transit gateway.

[[transit-gateway-name]]
=== Transit Gateway Name

Transit gateway attachment names can contain up to 255 alphanumeric characters (a-z, A-Z, 0-9) and hyphens (-).
Runtime Manager supports Unicode characters in private space names.

Use the same name for your transit gateway in AWS.
You can change this name later.

[[transit-gateway-region]]
=== Transit Gateway Region

The region corresponds to the location of your AWS Transit Gateway.

Your private space and AWS Transit Gateway must be in the same region.

[[transit-gateway-routing]]
=== Transit Gateway Routing

A maximum of 95 route table entries is permitted per VPC, regardless of the number of transit gateway attachments.
Consolidate networks to the fewest number possible to avoid exceeding the limit.

[[mulesoft-aws-account-id]]
=== MuleSoft AWS Account ID

The MuleSoft AWS account ID varies depending on your control plane, for example, US Cloud or EU Cloud,
and appears in *Add transit gateway* page when you select to create the transit gateway connection.

When you create a resource share in AWS, you specify this ID to allow Anypoint Platform to access the resource share.

If another team performs AWS configuration, share this MuleSoft AWS account ID with them.

[[resource-share-id-owner]]
=== Resource Share ID and Owner

The resource share ID and owner appear on the *Create a resource share* page on AWS.
You use these values to verify the resource share in Anypoint Platform.

* The resource share *ID* field contains alphanumeric characters (a-z, A-Z, 0-9) and hyphens (-).
* The resource share *Owner* field contains only numbers.


== See Also

* xref:ch2-private-space-about.adoc[]
* xref:ps-vpn-about.adoc[]
