= Deploying Mule Apps to Hyperforce

When deploying Mule Apps to Salesforce Hyperforce (Hyperforce), you deploy to a CloudHub 2.0 private or shared space. Consider the following guidelines.

== Before You Begin
Before deploying Mule apps to Hyperforce, review the following points:

* Hyperforce Instance +
Your MuleSoft account must have access to a Hyperforce instance. Contact your MuleSoft account representative to provision a MuleSoft license to a Hyperforce instance.

* Hyperforce Endpoints +
Hyperforce has a different base URL, exchange and platform endpoints. For a successful deployment change the Anypoint Platform endpoints URLs to the supported Hyperforce regions endpoints:

* xref:configure-mule-hyperforce.adoc[Configuring Mule to access Hyperforce]
* xref:exchange::to-publish-assets-maven.adoc[Publish assets using Maven]
* xref:url.adoc[Configure Hyperforce in Anypoint Code Builder]
* xref:url.adoc[Configure Hyperforce in Anypoint Studio]

== Deploy Mule Apps to Hyperforce
To deploy a Mule app to a Hyperforce instance, deploy the app to a CloudHub 2.0 private or shared space. For details, refer to xref:cloudhub-2::ch2-deploy.adoc[Deploying to CloudHub 2.0].

== See Also

* xref:configure-mule-hyperforce.adoc[Configuring Mule to Access Hyperforce]
* xref:index.adoc[Salesforce Hyperforce]